// Code generated by gen/repo. DO NOT EDIT.
// Code generated by gen/repo. DO NOT EDIT.
// Code generated by gen/repo. DO NOT EDIT.

package ai_boilerplate_repo

import (
	"context"
	"errors"
	"reflect"
	"strings"

	"github.com/fzf-labs/ai-boilerplate-backend/internal/data/gorm/ai_boilerplate_dao"
	"github.com/fzf-labs/ai-boilerplate-backend/internal/data/gorm/ai_boilerplate_model"
	"github.com/fzf-labs/godb/orm/condition"
	"github.com/fzf-labs/godb/orm/dbcache"
	"github.com/fzf-labs/godb/orm/encoding"
	"github.com/fzf-labs/godb/orm/gen/config"
	"github.com/jinzhu/copier"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

var _ IHelpCategoryRepo = (*HelpCategoryRepo)(nil)

var (
	CacheHelpCategoryByConditionPrefix         = "DBCache:ai_boilerplate:HelpCategoryByCondition"
	CacheHelpCategoryUnscopedByConditionPrefix = "DBCache:ai_boilerplate:HelpCategoryUnscopedByCondition"
	CacheHelpCategoryByIDPrefix                = "DBCache:ai_boilerplate:HelpCategoryByID"
	CacheHelpCategoryUnscopedByIDPrefix        = "DBCache:ai_boilerplate:HelpCategoryUnscopedByID"
	CacheHelpCategoryByOrderPrefix             = "DBCache:ai_boilerplate:HelpCategoryByOrder"
	CacheHelpCategoryUnscopedByOrderPrefix     = "DBCache:ai_boilerplate:HelpCategoryUnscopedByOrder"
)

type (
	IHelpCategoryRepo interface {
		// NewData 实例化
		NewData() *ai_boilerplate_model.HelpCategory
		// DeepCopy 深拷贝
		DeepCopy(data *ai_boilerplate_model.HelpCategory) *ai_boilerplate_model.HelpCategory
		// CreateOne 创建一条数据
		CreateOne(ctx context.Context, data *ai_boilerplate_model.HelpCategory) error
		// CreateOneCache 创建一条数据, 并删除缓存
		CreateOneCache(ctx context.Context, data *ai_boilerplate_model.HelpCategory) error
		// CreateOneByTx 创建一条数据(事务)
		CreateOneByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.HelpCategory) error
		// CreateOneCacheByTx 创建一条数据(事务), 并删除缓存
		CreateOneCacheByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.HelpCategory) error
		// CreateBatch 批量创建数据
		CreateBatch(ctx context.Context, data []*ai_boilerplate_model.HelpCategory, batchSize int) error
		// CreateBatchCache 批量创建数据, 并删除缓存
		CreateBatchCache(ctx context.Context, data []*ai_boilerplate_model.HelpCategory, batchSize int) error
		// CreateBatchByTx 批量创建数据(事务)
		CreateBatchByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data []*ai_boilerplate_model.HelpCategory, batchSize int) error
		// CreateBatchCacheByTx 批量创建数据(事务), 并删除缓存
		CreateBatchCacheByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data []*ai_boilerplate_model.HelpCategory, batchSize int) error
		// UpsertOne Upsert一条数据
		UpsertOne(ctx context.Context, data *ai_boilerplate_model.HelpCategory) error
		// UpsertOneCache Upsert一条数据, 并删除缓存
		UpsertOneCache(ctx context.Context, data *ai_boilerplate_model.HelpCategory) error
		// UpsertOneByTx Upsert一条数据(事务)
		UpsertOneByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.HelpCategory) error
		// UpsertOneCacheByTx Upsert一条数据(事务), 并删除缓存
		UpsertOneCacheByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.HelpCategory) error
		// UpsertOneByFields 根据fields字段Upsert一条数据
		UpsertOneByFields(ctx context.Context, data *ai_boilerplate_model.HelpCategory, fields []string) error
		// UpsertOneCacheByFields 根据fields字段Upsert一条数据, 并删除缓存
		UpsertOneCacheByFields(ctx context.Context, data *ai_boilerplate_model.HelpCategory, fields []string) error
		// UpsertOneByFieldsTx 根据fields字段Upsert一条数据(事务)
		UpsertOneByFieldsTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.HelpCategory, fields []string) error
		// UpsertOneCacheByFieldsTx 根据fields字段Upsert一条数据(事务), 并删除缓存
		UpsertOneCacheByFieldsTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.HelpCategory, fields []string) error
		// UpdateOne 更新一条数据
		UpdateOne(ctx context.Context, newData *ai_boilerplate_model.HelpCategory) error
		// UpdateOneUnscoped 更新一条数据（包括软删除）
		UpdateOneUnscoped(ctx context.Context, newData *ai_boilerplate_model.HelpCategory) error
		// UpdateOneCache 更新一条数据，并删除缓存
		UpdateOneCache(ctx context.Context, newData *ai_boilerplate_model.HelpCategory, oldData *ai_boilerplate_model.HelpCategory) error
		// UpdateOneUnscopedCache 更新一条数据，并删除缓存（包括软删除）
		UpdateOneUnscopedCache(ctx context.Context, newData *ai_boilerplate_model.HelpCategory, oldData *ai_boilerplate_model.HelpCategory) error
		// UpdateOneByTx 更新一条数据(事务)
		UpdateOneByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.HelpCategory) error
		// UpdateOneUnscopedByTx 更新一条数据(事务)（包括软删除）
		UpdateOneUnscopedByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.HelpCategory) error
		// UpdateOneCacheByTx 更新一条数据(事务)，并删除缓存
		UpdateOneCacheByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.HelpCategory, oldData *ai_boilerplate_model.HelpCategory) error
		// UpdateOneUnscopedCacheByTx 更新一条数据(事务)，并删除缓存（包括软删除）
		UpdateOneUnscopedCacheByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.HelpCategory, oldData *ai_boilerplate_model.HelpCategory) error
		// UpdateOneWithZero 更新一条数据,包含零值，并删除缓存
		UpdateOneWithZero(ctx context.Context, newData *ai_boilerplate_model.HelpCategory) error
		// UpdateOneUnscopedWithZero 更新一条数据,包含零值（包括软删除）
		UpdateOneUnscopedWithZero(ctx context.Context, newData *ai_boilerplate_model.HelpCategory) error
		// UpdateOneCacheWithZero 更新一条数据,包含零值，并删除缓存
		UpdateOneCacheWithZero(ctx context.Context, newData *ai_boilerplate_model.HelpCategory, oldData *ai_boilerplate_model.HelpCategory) error
		// UpdateOneUnscopedCacheWithZero 更新一条数据,包含零值，并删除缓存（包括软删除）
		UpdateOneUnscopedCacheWithZero(ctx context.Context, newData *ai_boilerplate_model.HelpCategory, oldData *ai_boilerplate_model.HelpCategory) error
		// UpdateOneWithZeroByTx 更新一条数据(事务),包含零值，并删除缓存
		UpdateOneWithZeroByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.HelpCategory) error
		// UpdateOneUnscopedWithZeroByTx 更新一条数据(事务),包含零值（包括软删除）
		UpdateOneUnscopedWithZeroByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.HelpCategory) error
		// UpdateOneCacheWithZeroByTx 更新一条数据(事务),包含零值，并删除缓存
		UpdateOneCacheWithZeroByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.HelpCategory, oldData *ai_boilerplate_model.HelpCategory) error
		// UpdateOneUnscopedCacheWithZeroByTx 更新一条数据(事务),包含零值，并删除缓存（包括软删除）
		UpdateOneUnscopedCacheWithZeroByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.HelpCategory, oldData *ai_boilerplate_model.HelpCategory) error
		// UpdateBatchByID 根据字段ID批量更新,零值会被更新
		UpdateBatchByID(ctx context.Context, ID string, data map[string]interface{}) error
		// UpdateBatchUnscopedByID 根据字段ID批量更新,零值会被更新（包括软删除）
		UpdateBatchUnscopedByID(ctx context.Context, ID string, data map[string]interface{}) error
		// UpdateBatchByIDTx 根据主键ID批量更新(事务),零值会被更新
		UpdateBatchByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string, data map[string]interface{}) error
		// UpdateBatchUnscopedByIDTx 根据主键ID批量更新(事务),零值会被更新（包括软删除）
		UpdateBatchUnscopedByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string, data map[string]interface{}) error
		// UpdateBatchByIDS 根据字段IDS批量更新,零值会被更新
		UpdateBatchByIDS(ctx context.Context, IDS []string, data map[string]interface{}) error
		// UpdateBatchUnscopedByIDS 根据字段IDS批量更新,零值会被更新（包括软删除）
		UpdateBatchUnscopedByIDS(ctx context.Context, IDS []string, data map[string]interface{}) error
		// UpdateBatchByIDSTx 根据字段IDS批量更新(事务),零值会被更新
		UpdateBatchByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string, data map[string]interface{}) error
		// UpdateBatchUnscopedByIDSTx 根据字段IDS批量更新(事务),零值会被更新（包括软删除）
		UpdateBatchUnscopedByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string, data map[string]interface{}) error
		// UpdateBatchByOrder 根据字段Order批量更新,零值会被更新
		UpdateBatchByOrder(ctx context.Context, order int32, data map[string]interface{}) error
		// UpdateBatchUnscopedByOrder 根据字段Order批量更新,零值会被更新（包括软删除）
		UpdateBatchUnscopedByOrder(ctx context.Context, order int32, data map[string]interface{}) error
		// UpdateBatchByOrderTx 根据主键Order批量更新(事务),零值会被更新
		UpdateBatchByOrderTx(ctx context.Context, tx *ai_boilerplate_dao.Query, order int32, data map[string]interface{}) error
		// UpdateBatchUnscopedByOrderTx 根据主键Order批量更新(事务),零值会被更新（包括软删除）
		UpdateBatchUnscopedByOrderTx(ctx context.Context, tx *ai_boilerplate_dao.Query, order int32, data map[string]interface{}) error
		// UpdateBatchByOrders 根据字段Orders批量更新,零值会被更新
		UpdateBatchByOrders(ctx context.Context, orders []int32, data map[string]interface{}) error
		// UpdateBatchUnscopedByOrders 根据字段Orders批量更新,零值会被更新（包括软删除）
		UpdateBatchUnscopedByOrders(ctx context.Context, orders []int32, data map[string]interface{}) error
		// UpdateBatchByOrdersTx 根据字段Orders批量更新(事务),零值会被更新
		UpdateBatchByOrdersTx(ctx context.Context, tx *ai_boilerplate_dao.Query, orders []int32, data map[string]interface{}) error
		// UpdateBatchUnscopedByOrdersTx 根据字段Orders批量更新(事务),零值会被更新（包括软删除）
		UpdateBatchUnscopedByOrdersTx(ctx context.Context, tx *ai_boilerplate_dao.Query, orders []int32, data map[string]interface{}) error
		// FindOneByID 根据ID查询一条数据
		FindOneByID(ctx context.Context, ID string) (*ai_boilerplate_model.HelpCategory, error)
		// FindOneUnscopedByID 根据ID查询一条数据（包括软删除）
		FindOneUnscopedByID(ctx context.Context, ID string) (*ai_boilerplate_model.HelpCategory, error)
		// FindOneCacheByID 根据ID查询一条数据，并设置缓存
		FindOneCacheByID(ctx context.Context, ID string) (*ai_boilerplate_model.HelpCategory, error)
		// FindOneUnscopedCacheByID 根据ID查询一条数据（包括软删除），并设置缓存
		FindOneUnscopedCacheByID(ctx context.Context, ID string) (*ai_boilerplate_model.HelpCategory, error)
		// FindMultiByIDS 根据IDS查询多条数据
		FindMultiByIDS(ctx context.Context, IDS []string) ([]*ai_boilerplate_model.HelpCategory, error)
		// FindMultiUnscopedByIDS 根据IDS查询多条数据（包括软删除）
		FindMultiUnscopedByIDS(ctx context.Context, IDS []string) ([]*ai_boilerplate_model.HelpCategory, error)
		// FindMultiCacheByIDS 根据IDS查询多条数据，并设置缓存
		FindMultiCacheByIDS(ctx context.Context, IDS []string) ([]*ai_boilerplate_model.HelpCategory, error)
		// FindMultiUnscopedCacheByIDS 根据IDS查询多条数据（包括软删除），并设置缓存
		FindMultiUnscopedCacheByIDS(ctx context.Context, IDS []string) ([]*ai_boilerplate_model.HelpCategory, error)
		// FindMultiByOrder 根据order查询多条数据
		FindMultiByOrder(ctx context.Context, order int32) ([]*ai_boilerplate_model.HelpCategory, error)
		// FindMultiUnscopedByOrder 根据order查询多条数据（包括软删除）
		FindMultiUnscopedByOrder(ctx context.Context, order int32) ([]*ai_boilerplate_model.HelpCategory, error)
		// FindMultiCacheByOrder 根据order查询多条数据并设置缓存
		FindMultiCacheByOrder(ctx context.Context, order int32) ([]*ai_boilerplate_model.HelpCategory, error)
		// FindMultiUnscopedCacheByOrder 根据order查询多条数据（包括软删除）并设置缓存
		FindMultiUnscopedCacheByOrder(ctx context.Context, order int32) ([]*ai_boilerplate_model.HelpCategory, error)
		// FindMultiByOrders 根据orders查询多条数据
		FindMultiByOrders(ctx context.Context, orders []int32) ([]*ai_boilerplate_model.HelpCategory, error)
		// FindMultiUnscopedByOrders 根据orders查询多条数据（包括软删除）
		FindMultiUnscopedByOrders(ctx context.Context, orders []int32) ([]*ai_boilerplate_model.HelpCategory, error)
		// FindMultiCacheByOrders 根据orders查询多条数据，并设置缓存
		FindMultiCacheByOrders(ctx context.Context, orders []int32) ([]*ai_boilerplate_model.HelpCategory, error)
		// FindMultiUnscopedCacheByOrders 根据orders查询多条数据（包括软删除），并设置缓存
		FindMultiUnscopedCacheByOrders(ctx context.Context, orders []int32) ([]*ai_boilerplate_model.HelpCategory, error)
		// FindMultiByCondition 自定义查询数据(通用)
		FindMultiByCondition(ctx context.Context, conditionReq *condition.Req) ([]*ai_boilerplate_model.HelpCategory, *condition.Reply, error)
		// FindMultiUnscopedByCondition 自定义查询数据(通用)（包括软删除）
		FindMultiUnscopedByCondition(ctx context.Context, conditionReq *condition.Req) ([]*ai_boilerplate_model.HelpCategory, *condition.Reply, error)
		// FindMultiCacheByCondition 自定义查询数据(通用),并设置缓存
		FindMultiCacheByCondition(ctx context.Context, conditionReq *condition.Req) ([]*ai_boilerplate_model.HelpCategory, *condition.Reply, error)
		// FindMultiUnscopedCacheByCondition 自定义查询数据(通用)（包括软删除）,并设置缓存
		FindMultiUnscopedCacheByCondition(ctx context.Context, conditionReq *condition.Req) ([]*ai_boilerplate_model.HelpCategory, *condition.Reply, error)
		// DeleteOneByID 根据ID删除一条数据
		DeleteOneByID(ctx context.Context, ID string) error
		// DeleteOneUnscopedByID 根据ID删除一条数据
		DeleteOneUnscopedByID(ctx context.Context, ID string) error
		// DeleteOneCacheByID 根据ID删除一条数据，并删除缓存
		DeleteOneCacheByID(ctx context.Context, ID string) error
		// DeleteOneUnscopedCacheByID 根据ID删除一条数据，并删除缓存
		DeleteOneUnscopedCacheByID(ctx context.Context, ID string) error
		// DeleteOneByIDTx 根据ID删除一条数据(事务)
		DeleteOneByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string) error
		// DeleteOneUnscopedByIDTx 根据ID删除一条数据(事务)
		DeleteOneUnscopedByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string) error
		// DeleteOneCacheByIDTx 根据ID删除一条数据，并删除缓存(事务)
		DeleteOneCacheByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string) error
		// DeleteOneUnscopedCacheByIDTx 根据ID删除一条数据，并删除缓存(事务)
		DeleteOneUnscopedCacheByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string) error
		// DeleteMultiByIDS 根据IDS删除多条数据
		DeleteMultiByIDS(ctx context.Context, IDS []string) error
		// DeleteMultiUnscopedByIDS 根据IDS删除多条数据
		DeleteMultiUnscopedByIDS(ctx context.Context, IDS []string) error
		// DeleteMultiCacheByIDS 根据IDS删除多条数据，并删除缓存
		DeleteMultiCacheByIDS(ctx context.Context, IDS []string) error
		// DeleteMultiUnscopedCacheByIDS 根据IDS删除多条数据，并删除缓存
		DeleteMultiUnscopedCacheByIDS(ctx context.Context, IDS []string) error
		// DeleteMultiByIDSTx 根据IDS删除多条数据(事务)
		DeleteMultiByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string) error
		// DeleteMultiUnscopedByIDSTx 根据IDS删除多条数据(事务)
		DeleteMultiUnscopedByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string) error
		// DeleteMultiCacheByIDSTx 根据IDS删除多条数据，并删除缓存(事务)
		DeleteMultiCacheByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string) error
		// DeleteMultiUnscopedCacheByIDSTx 根据IDS删除多条数据，并删除缓存(事务)
		DeleteMultiUnscopedCacheByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string) error
		// DeleteMultiByOrder 根据Order删除多条数据
		DeleteMultiByOrder(ctx context.Context, order int32) error
		// DeleteMultiUnscopedByOrder 根据Order删除多条数据
		DeleteMultiUnscopedByOrder(ctx context.Context, order int32) error
		// DeleteMultiCacheByOrder 根据order删除多条数据，并删除缓存
		DeleteMultiCacheByOrder(ctx context.Context, order int32) error
		// DeleteMultiUnscopedCacheByOrder 根据order删除多条数据，并删除缓存
		DeleteMultiUnscopedCacheByOrder(ctx context.Context, order int32) error
		// DeleteMultiByOrderTx 根据order删除多条数据
		DeleteMultiByOrderTx(ctx context.Context, tx *ai_boilerplate_dao.Query, order int32) error
		// DeleteMultiUnscopedByOrderTx 根据order删除多条数据
		DeleteMultiUnscopedByOrderTx(ctx context.Context, tx *ai_boilerplate_dao.Query, order int32) error
		// DeleteMultiCacheByOrderTx 根据order删除多条数据，并删除缓存
		DeleteMultiCacheByOrderTx(ctx context.Context, tx *ai_boilerplate_dao.Query, order int32) error
		// DeleteMultiUnscopedCacheByOrderTx 根据order删除多条数据，并删除缓存
		DeleteMultiUnscopedCacheByOrderTx(ctx context.Context, tx *ai_boilerplate_dao.Query, order int32) error
		// DeleteMultiByOrders 根据Orders删除多条数据
		DeleteMultiByOrders(ctx context.Context, orders []int32) error
		// DeleteMultiUnscopedByOrders 根据Orders删除多条数据
		DeleteMultiUnscopedByOrders(ctx context.Context, orders []int32) error
		// DeleteMultiCacheByOrders 根据Orders删除多条数据，并删除缓存
		DeleteMultiCacheByOrders(ctx context.Context, orders []int32) error
		// DeleteMultiUnscopedCacheByOrders 根据Orders删除多条数据，并删除缓存
		DeleteMultiUnscopedCacheByOrders(ctx context.Context, orders []int32) error
		// DeleteMultiByOrdersTx 根据Orders删除多条数据(事务)
		DeleteMultiByOrdersTx(ctx context.Context, tx *ai_boilerplate_dao.Query, orders []int32) error
		// DeleteMultiUnscopedByOrdersTx 根据Orders删除多条数据(事务)
		DeleteMultiUnscopedByOrdersTx(ctx context.Context, tx *ai_boilerplate_dao.Query, orders []int32) error
		// DeleteMultiCacheByOrdersTx 根据Orders删除多条数据，并删除缓存(事务)
		DeleteMultiCacheByOrdersTx(ctx context.Context, tx *ai_boilerplate_dao.Query, orders []int32) error
		// DeleteMultiUnscopedCacheByOrdersTx 根据Orders删除多条数据，并删除缓存(事务)
		DeleteMultiUnscopedCacheByOrdersTx(ctx context.Context, tx *ai_boilerplate_dao.Query, orders []int32) error
		// DeleteIndexCache 删除索引存在的缓存
		DeleteIndexCache(ctx context.Context, data ...*ai_boilerplate_model.HelpCategory) error
	}
	HelpCategoryRepo struct {
		db       *gorm.DB
		cache    dbcache.IDBCache
		encoding encoding.API
	}
)

func NewHelpCategoryRepo(cfg *config.Repo) *HelpCategoryRepo {
	return &HelpCategoryRepo{
		db:       cfg.DB,
		cache:    cfg.Cache,
		encoding: cfg.Encoding,
	}
}

// NewData 实例化
func (h *HelpCategoryRepo) NewData() *ai_boilerplate_model.HelpCategory {
	return &ai_boilerplate_model.HelpCategory{}
}

// DeepCopy 深拷贝
func (h *HelpCategoryRepo) DeepCopy(data *ai_boilerplate_model.HelpCategory) *ai_boilerplate_model.HelpCategory {
	newData := new(ai_boilerplate_model.HelpCategory)
	_ = copier.CopyWithOption(newData, data, copier.Option{DeepCopy: true})
	return newData
}

// CreateOne 创建一条数据
func (h *HelpCategoryRepo) CreateOne(ctx context.Context, data *ai_boilerplate_model.HelpCategory) error {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	err := dao.WithContext(ctx).Create(data)
	if err != nil {
		return err
	}
	return nil
}

// CreateOneCache 创建一条数据, 并删除缓存
func (h *HelpCategoryRepo) CreateOneCache(ctx context.Context, data *ai_boilerplate_model.HelpCategory) error {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	err := dao.WithContext(ctx).Create(data)
	if err != nil {
		return err
	}
	err = h.DeleteIndexCache(ctx, data)
	if err != nil {
		return err
	}
	return nil
}

// CreateOneByTx 创建一条数据(事务)
func (h *HelpCategoryRepo) CreateOneByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.HelpCategory) error {
	dao := tx.HelpCategory
	err := dao.WithContext(ctx).Create(data)
	if err != nil {
		return err
	}
	return nil
}

// CreateOneCacheByTx 创建一条数据(事务), 并删除缓存
func (h *HelpCategoryRepo) CreateOneCacheByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.HelpCategory) error {
	dao := tx.HelpCategory
	err := dao.WithContext(ctx).Create(data)
	if err != nil {
		return err
	}
	err = h.DeleteIndexCache(ctx, data)
	if err != nil {
		return err
	}
	return nil
}

// CreateBatch 批量创建数据
func (h *HelpCategoryRepo) CreateBatch(ctx context.Context, data []*ai_boilerplate_model.HelpCategory, batchSize int) error {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	err := dao.WithContext(ctx).CreateInBatches(data, batchSize)
	if err != nil {
		return err
	}
	return nil
}

// CreateBatchCache 批量创建数据, 并删除缓存
func (h *HelpCategoryRepo) CreateBatchCache(ctx context.Context, data []*ai_boilerplate_model.HelpCategory, batchSize int) error {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	err := dao.WithContext(ctx).CreateInBatches(data, batchSize)
	if err != nil {
		return err
	}
	err = h.DeleteIndexCache(ctx, data...)
	if err != nil {
		return err
	}
	return nil
}

// CreateBatchByTx 批量创建数据(事务)
func (h *HelpCategoryRepo) CreateBatchByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data []*ai_boilerplate_model.HelpCategory, batchSize int) error {
	dao := tx.HelpCategory
	err := dao.WithContext(ctx).CreateInBatches(data, batchSize)
	if err != nil {
		return err
	}
	return nil
}

// CreateBatchCacheByTx 批量创建数据(事务), 并删除缓存
func (h *HelpCategoryRepo) CreateBatchCacheByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data []*ai_boilerplate_model.HelpCategory, batchSize int) error {
	dao := tx.HelpCategory
	err := dao.WithContext(ctx).CreateInBatches(data, batchSize)
	if err != nil {
		return err
	}
	err = h.DeleteIndexCache(ctx, data...)
	if err != nil {
		return err
	}
	return nil
}

// UpsertOne Upsert一条数据
// Update all columns, except primary keys, to new value on conflict
func (h *HelpCategoryRepo) UpsertOne(ctx context.Context, data *ai_boilerplate_model.HelpCategory) error {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	err := dao.WithContext(ctx).Save(data)
	if err != nil {
		return err
	}
	return nil
}

// UpsertOneCache Upsert一条数据, 并删除缓存
// Update all columns, except primary keys, to new value on conflict
func (h *HelpCategoryRepo) UpsertOneCache(ctx context.Context, data *ai_boilerplate_model.HelpCategory) error {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	oldData, err := dao.WithContext(ctx).Where(dao.ID.Eq(data.ID)).Unscoped().First()
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return err
	}
	err = dao.WithContext(ctx).Save(data)
	if err != nil {
		return err
	}
	err = h.DeleteIndexCache(ctx, oldData, data)
	if err != nil {
		return err
	}
	return nil
}

// UpsertOneByTx Upsert一条数据(事务)
// Update all columns, except primary keys, to new value on conflict
func (h *HelpCategoryRepo) UpsertOneByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.HelpCategory) error {
	dao := tx.HelpCategory
	err := dao.WithContext(ctx).Save(data)
	if err != nil {
		return err
	}
	return nil
}

// UpsertOneCacheByTx Upsert一条数据(事务), 并删除缓存
// Update all columns, except primary keys, to new value on conflict
func (h *HelpCategoryRepo) UpsertOneCacheByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.HelpCategory) error {
	dao := tx.HelpCategory
	oldData, err := dao.WithContext(ctx).Where(dao.ID.Eq(data.ID)).Unscoped().First()
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return err
	}
	err = dao.WithContext(ctx).Save(data)
	if err != nil {
		return err
	}
	err = h.DeleteIndexCache(ctx, oldData, data)
	if err != nil {
		return err
	}
	return nil
}

// UpsertOneByFields 根据fields字段Upsert一条数据
func (h *HelpCategoryRepo) UpsertOneByFields(ctx context.Context, data *ai_boilerplate_model.HelpCategory, fields []string) error {
	if len(fields) == 0 {
		return errors.New("UpsertOneByFields fields is empty")
	}
	columns := make([]clause.Column, 0)
	for _, item := range fields {
		columns = append(columns, clause.Column{Name: item})
	}
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	err := dao.WithContext(ctx).Clauses(clause.OnConflict{
		Columns:   columns,
		UpdateAll: true,
	}).Create(data)
	if err != nil {
		return err
	}
	return nil
}

// UpsertOneCacheByFields 根据fields字段Upsert一条数据, 并删除缓存
func (h *HelpCategoryRepo) UpsertOneCacheByFields(ctx context.Context, data *ai_boilerplate_model.HelpCategory, fields []string) error {
	if len(fields) == 0 {
		return errors.New("UpsertOneByFields fields is empty")
	}
	fieldNameToValue := make(map[string]interface{})
	typ := reflect.TypeOf(data).Elem()
	val := reflect.ValueOf(data).Elem()
	for i := 0; i < typ.NumField(); i++ {
		field := typ.Field(i)
		gormTag := field.Tag.Get("gorm")
		if gormTag != "" {
			gormTags := strings.Split(gormTag, ";")
			for _, item := range gormTags {
				if strings.Contains(item, "column") {
					columnName := strings.TrimPrefix(item, "column:")
					fieldValue := val.Field(i).Interface()
					fieldNameToValue[columnName] = fieldValue
					break
				}
			}
		}
	}
	whereExpressions := make([]clause.Expression, 0)
	columns := make([]clause.Column, 0)
	for _, item := range fields {
		whereExpressions = append(whereExpressions, clause.And(clause.Eq{Column: item, Value: fieldNameToValue[item]}))
		columns = append(columns, clause.Column{Name: item})
	}
	oldData := &ai_boilerplate_model.HelpCategory{}
	err := h.db.Model(&ai_boilerplate_model.HelpCategory{}).Clauses(whereExpressions...).Unscoped().First(oldData).Error
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return err
	}
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	err = dao.WithContext(ctx).Clauses(clause.OnConflict{
		Columns:   columns,
		UpdateAll: true,
	}).Create(data)
	if err != nil {
		return err
	}
	err = h.DeleteIndexCache(ctx, oldData, data)
	if err != nil {
		return err
	}
	return nil
}

// UpsertOneByFieldsTx 根据fields字段Upsert一条数据(事务)
func (h *HelpCategoryRepo) UpsertOneByFieldsTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.HelpCategory, fields []string) error {
	if len(fields) == 0 {
		return errors.New("UpsertOneByFieldsTx fields is empty")
	}
	columns := make([]clause.Column, 0)
	for _, item := range fields {
		columns = append(columns, clause.Column{Name: item})
	}
	dao := tx.HelpCategory
	err := dao.WithContext(ctx).Clauses(clause.OnConflict{
		Columns:   columns,
		UpdateAll: true,
	}).Create(data)
	if err != nil {
		return err
	}
	return nil
}

// UpsertOneCacheByFieldsTx 根据fields字段Upsert一条数据(事务), 并删除缓存
func (h *HelpCategoryRepo) UpsertOneCacheByFieldsTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.HelpCategory, fields []string) error {
	if len(fields) == 0 {
		return errors.New("UpsertOneByFieldsTx fields is empty")
	}
	fieldNameToValue := make(map[string]interface{})
	typ := reflect.TypeOf(data).Elem()
	val := reflect.ValueOf(data).Elem()
	for i := 0; i < typ.NumField(); i++ {
		field := typ.Field(i)
		gormTag := field.Tag.Get("gorm")
		if gormTag != "" {
			gormTags := strings.Split(gormTag, ";")
			for _, item := range gormTags {
				if strings.Contains(item, "column") {
					columnName := strings.TrimPrefix(item, "column:")
					fieldValue := val.Field(i).Interface()
					fieldNameToValue[columnName] = fieldValue
					break
				}
			}
		}
	}
	whereExpressions := make([]clause.Expression, 0)
	columns := make([]clause.Column, 0)
	for _, item := range fields {
		whereExpressions = append(whereExpressions, clause.And(clause.Eq{Column: item, Value: fieldNameToValue[item]}))
		columns = append(columns, clause.Column{Name: item})
	}
	oldData := &ai_boilerplate_model.HelpCategory{}
	err := h.db.Model(&ai_boilerplate_model.HelpCategory{}).Clauses(whereExpressions...).Unscoped().First(oldData).Error
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return err
	}
	dao := tx.HelpCategory
	err = dao.WithContext(ctx).Clauses(clause.OnConflict{
		Columns:   columns,
		UpdateAll: true,
	}).Create(data)
	if err != nil {
		return err
	}
	err = h.DeleteIndexCache(ctx, oldData, data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOne 更新一条数据
// data 中主键字段必须有值，零值不会被更新
func (h *HelpCategoryRepo) UpdateOne(ctx context.Context, newData *ai_boilerplate_model.HelpCategory) error {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	_, err := dao.WithContext(ctx).Updates(newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneUnscoped 更新一条数据（包括软删除）
// data 中主键字段必须有值，零值不会被更新
func (h *HelpCategoryRepo) UpdateOneUnscoped(ctx context.Context, newData *ai_boilerplate_model.HelpCategory) error {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	_, err := dao.WithContext(ctx).Unscoped().Updates(newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneCache 更新一条数据，并删除缓存
// data 中主键字段必须有值，零值不会被更新
// oldData 旧数据，删除缓存时使用
func (h *HelpCategoryRepo) UpdateOneCache(ctx context.Context, newData *ai_boilerplate_model.HelpCategory, oldData *ai_boilerplate_model.HelpCategory) error {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	_, err := dao.WithContext(ctx).Updates(newData)
	if err != nil {
		return err
	}
	err = h.DeleteIndexCache(ctx, oldData, newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneUnscopedCache 更新一条数据，并删除缓存（包括软删除）
// data 中主键字段必须有值，零值不会被更新
// oldData 旧数据，删除缓存时使用
func (h *HelpCategoryRepo) UpdateOneUnscopedCache(ctx context.Context, newData *ai_boilerplate_model.HelpCategory, oldData *ai_boilerplate_model.HelpCategory) error {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	_, err := dao.WithContext(ctx).Unscoped().Updates(newData)
	if err != nil {
		return err
	}
	err = h.DeleteIndexCache(ctx, oldData, newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneByTx 更新一条数据(事务)
// data 中主键字段必须有值，零值不会被更新
func (h *HelpCategoryRepo) UpdateOneByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.HelpCategory) error {
	dao := tx.HelpCategory
	_, err := dao.WithContext(ctx).Updates(newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneUnscopedByTx 更新一条数据(事务)（包括软删除）
// data 中主键字段必须有值，零值不会被更新
func (h *HelpCategoryRepo) UpdateOneUnscopedByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.HelpCategory) error {
	dao := tx.HelpCategory
	_, err := dao.WithContext(ctx).Unscoped().Updates(newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneCacheByTx 更新一条数据(事务)，并删除缓存
// data 中主键字段必须有值，零值不会被更新
// oldData 旧数据，删除缓存时使用
func (h *HelpCategoryRepo) UpdateOneCacheByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.HelpCategory, oldData *ai_boilerplate_model.HelpCategory) error {
	dao := tx.HelpCategory
	_, err := dao.WithContext(ctx).Updates(newData)
	if err != nil {
		return err
	}
	err = h.DeleteIndexCache(ctx, oldData, newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneUnscopedCacheByTx 更新一条数据(事务)，并删除缓存（包括软删除）
// data 中主键字段必须有值，零值不会被更新
// oldData 旧数据，删除缓存时使用
func (h *HelpCategoryRepo) UpdateOneUnscopedCacheByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.HelpCategory, oldData *ai_boilerplate_model.HelpCategory) error {
	dao := tx.HelpCategory
	_, err := dao.WithContext(ctx).Unscoped().Updates(newData)
	if err != nil {
		return err
	}
	err = h.DeleteIndexCache(ctx, oldData, newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneWithZero 更新一条数据,包含零值
// data 中主键字段必须有值,并且会更新所有字段,包括零值
func (h *HelpCategoryRepo) UpdateOneWithZero(ctx context.Context, newData *ai_boilerplate_model.HelpCategory) error {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	_, err := dao.WithContext(ctx).Select(dao.ALL.WithTable("")).Updates(newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneUnscopedWithZero 更新一条数据,包含零值（包括软删除）
// data 中主键字段必须有值,并且会更新所有字段,包括零值
func (h *HelpCategoryRepo) UpdateOneUnscopedWithZero(ctx context.Context, newData *ai_boilerplate_model.HelpCategory) error {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	_, err := dao.WithContext(ctx).Unscoped().Select(dao.ALL.WithTable("")).Updates(newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneCacheWithZero 更新一条数据,包含零值，并删除缓存
// data 中主键字段必须有值,并且会更新所有字段,包括零值
// oldData 旧数据，删除缓存时使用
func (h *HelpCategoryRepo) UpdateOneCacheWithZero(ctx context.Context, newData *ai_boilerplate_model.HelpCategory, oldData *ai_boilerplate_model.HelpCategory) error {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	_, err := dao.WithContext(ctx).Select(dao.ALL.WithTable("")).Updates(newData)
	if err != nil {
		return err
	}
	err = h.DeleteIndexCache(ctx, oldData, newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneUnscopedCacheWithZero 更新一条数据,包含零值，并删除缓存（包括软删除）
// data 中主键字段必须有值,并且会更新所有字段,包括零值
// oldData 旧数据，删除缓存时使用
func (h *HelpCategoryRepo) UpdateOneUnscopedCacheWithZero(ctx context.Context, newData *ai_boilerplate_model.HelpCategory, oldData *ai_boilerplate_model.HelpCategory) error {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	_, err := dao.WithContext(ctx).Unscoped().Select(dao.ALL.WithTable("")).Updates(newData)
	if err != nil {
		return err
	}
	err = h.DeleteIndexCache(ctx, oldData, newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneWithZeroByTx 更新一条数据(事务),包含零值，
// data 中主键字段必须有值,并且会更新所有字段,包括零值
func (h *HelpCategoryRepo) UpdateOneWithZeroByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.HelpCategory) error {
	dao := tx.HelpCategory
	_, err := dao.WithContext(ctx).Select(dao.ALL.WithTable("")).Updates(newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneUnscopedWithZeroByTx 更新一条数据(事务),包含零值（包括软删除）
// data 中主键字段必须有值,并且会更新所有字段,包括零值
func (h *HelpCategoryRepo) UpdateOneUnscopedWithZeroByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.HelpCategory) error {
	dao := tx.HelpCategory
	_, err := dao.WithContext(ctx).Unscoped().Select(dao.ALL.WithTable("")).Updates(newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneCacheWithZeroByTx 更新一条数据(事务),包含零值，并删除缓存
// data 中主键字段必须有值,并且会更新所有字段,包括零值
// oldData 旧数据，删除缓存时使用
func (h *HelpCategoryRepo) UpdateOneCacheWithZeroByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.HelpCategory, oldData *ai_boilerplate_model.HelpCategory) error {
	dao := tx.HelpCategory
	_, err := dao.WithContext(ctx).Select(dao.ALL.WithTable("")).Updates(newData)
	if err != nil {
		return err
	}
	err = h.DeleteIndexCache(ctx, oldData, newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneUnscopedCacheWithZeroByTx 更新一条数据(事务),包含零值，并删除缓存（包括软删除）
// data 中主键字段必须有值,并且会更新所有字段,包括零值
// oldData 旧数据，删除缓存时使用
func (h *HelpCategoryRepo) UpdateOneUnscopedCacheWithZeroByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.HelpCategory, oldData *ai_boilerplate_model.HelpCategory) error {
	dao := tx.HelpCategory
	_, err := dao.WithContext(ctx).Unscoped().Select(dao.ALL.WithTable("")).Updates(newData)
	if err != nil {
		return err
	}
	err = h.DeleteIndexCache(ctx, oldData, newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchByID 根据字段ID批量更新,零值会被更新
func (h *HelpCategoryRepo) UpdateBatchByID(ctx context.Context, ID string, data map[string]interface{}) error {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	_, err := dao.WithContext(ctx).Where(dao.ID.Eq(ID)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchUnscopedByID 根据字段ID批量更新,零值会被更新（包括软删除）
func (h *HelpCategoryRepo) UpdateBatchUnscopedByID(ctx context.Context, ID string, data map[string]interface{}) error {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.Eq(ID)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchByIDTx 根据字段ID批量更新(事务),零值会被更新
func (h *HelpCategoryRepo) UpdateBatchByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string, data map[string]interface{}) error {
	dao := tx.HelpCategory
	_, err := dao.WithContext(ctx).Where(dao.ID.Eq(ID)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchUnscopedByIDTx 根据字段ID批量更新(事务),零值会被更新（包括软删除）
func (h *HelpCategoryRepo) UpdateBatchUnscopedByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string, data map[string]interface{}) error {
	dao := tx.HelpCategory
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.Eq(ID)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchByIDS 根据字段IDS批量更新,零值会被更新
func (h *HelpCategoryRepo) UpdateBatchByIDS(ctx context.Context, IDS []string, data map[string]interface{}) error {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	_, err := dao.WithContext(ctx).Where(dao.ID.In(IDS...)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchUnscopedByIDS 根据字段IDS批量更新,零值会被更新（包括软删除）
func (h *HelpCategoryRepo) UpdateBatchUnscopedByIDS(ctx context.Context, IDS []string, data map[string]interface{}) error {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.In(IDS...)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchByIDSTx 根据字段IDS批量更新(事务),零值会被更新
func (h *HelpCategoryRepo) UpdateBatchByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string, data map[string]interface{}) error {
	dao := tx.HelpCategory
	_, err := dao.WithContext(ctx).Where(dao.ID.In(IDS...)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchUnscopedByIDSTx 根据字段IDS批量更新(事务),零值会被更新（包括软删除）
func (h *HelpCategoryRepo) UpdateBatchUnscopedByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string, data map[string]interface{}) error {
	dao := tx.HelpCategory
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.In(IDS...)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchByOrder 根据字段Order批量更新,零值会被更新
func (h *HelpCategoryRepo) UpdateBatchByOrder(ctx context.Context, order int32, data map[string]interface{}) error {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	_, err := dao.WithContext(ctx).Where(dao.Order.Eq(order)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchUnscopedByOrder 根据字段Order批量更新,零值会被更新（包括软删除）
func (h *HelpCategoryRepo) UpdateBatchUnscopedByOrder(ctx context.Context, order int32, data map[string]interface{}) error {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.Order.Eq(order)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchByOrderTx 根据字段Order批量更新(事务),零值会被更新
func (h *HelpCategoryRepo) UpdateBatchByOrderTx(ctx context.Context, tx *ai_boilerplate_dao.Query, order int32, data map[string]interface{}) error {
	dao := tx.HelpCategory
	_, err := dao.WithContext(ctx).Where(dao.Order.Eq(order)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchUnscopedByOrderTx 根据字段Order批量更新(事务),零值会被更新（包括软删除）
func (h *HelpCategoryRepo) UpdateBatchUnscopedByOrderTx(ctx context.Context, tx *ai_boilerplate_dao.Query, order int32, data map[string]interface{}) error {
	dao := tx.HelpCategory
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.Order.Eq(order)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchByOrders 根据字段Orders批量更新,零值会被更新
func (h *HelpCategoryRepo) UpdateBatchByOrders(ctx context.Context, orders []int32, data map[string]interface{}) error {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	_, err := dao.WithContext(ctx).Where(dao.Order.In(orders...)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchUnscopedByOrders 根据字段Orders批量更新,零值会被更新（包括软删除）
func (h *HelpCategoryRepo) UpdateBatchUnscopedByOrders(ctx context.Context, orders []int32, data map[string]interface{}) error {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.Order.In(orders...)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchByOrdersTx 根据字段Orders批量更新(事务),零值会被更新
func (h *HelpCategoryRepo) UpdateBatchByOrdersTx(ctx context.Context, tx *ai_boilerplate_dao.Query, orders []int32, data map[string]interface{}) error {
	dao := tx.HelpCategory
	_, err := dao.WithContext(ctx).Where(dao.Order.In(orders...)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchUnscopedByOrdersTx 根据字段Orders批量更新(事务),零值会被更新（包括软删除）
func (h *HelpCategoryRepo) UpdateBatchUnscopedByOrdersTx(ctx context.Context, tx *ai_boilerplate_dao.Query, orders []int32, data map[string]interface{}) error {
	dao := tx.HelpCategory
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.Order.In(orders...)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// FindOneByID 根据ID查询一条数据
func (h *HelpCategoryRepo) FindOneByID(ctx context.Context, ID string) (*ai_boilerplate_model.HelpCategory, error) {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	result, err := dao.WithContext(ctx).Where(dao.ID.Eq(ID)).First()
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, err
	}
	return result, nil
}

// FindOneUnscopedByID 根据ID查询一条数据（包括软删除）
func (h *HelpCategoryRepo) FindOneUnscopedByID(ctx context.Context, ID string) (*ai_boilerplate_model.HelpCategory, error) {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.Eq(ID)).First()
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, err
	}
	return result, nil
}

// FindOneCacheByID 根据ID查询一条数据，并设置缓存
func (h *HelpCategoryRepo) FindOneCacheByID(ctx context.Context, ID string) (*ai_boilerplate_model.HelpCategory, error) {
	resp := new(ai_boilerplate_model.HelpCategory)
	cacheKey := h.cache.Key(CacheHelpCategoryByIDPrefix, ID)
	cacheValue, err := h.cache.Fetch(ctx, cacheKey, func() (string, error) {
		dao := ai_boilerplate_dao.Use(h.db).HelpCategory
		result, err := dao.WithContext(ctx).Where(dao.ID.Eq(ID)).First()
		if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
			return "", err
		}
		marshal, err := h.encoding.Marshal(result)
		if err != nil {
			return "", err
		}
		return string(marshal), nil
	}, h.cache.TTL())
	if err != nil {
		return nil, err
	}
	if cacheValue != "" {
		err = h.encoding.Unmarshal([]byte(cacheValue), resp)
		if err != nil {
			return nil, err
		}
	}
	return resp, nil
}

// FindOneUnscopedCacheByID 根据ID查询一条数据（包括软删除），并设置缓存
func (h *HelpCategoryRepo) FindOneUnscopedCacheByID(ctx context.Context, ID string) (*ai_boilerplate_model.HelpCategory, error) {
	resp := new(ai_boilerplate_model.HelpCategory)
	cacheKey := h.cache.Key(CacheHelpCategoryUnscopedByIDPrefix, ID)
	cacheValue, err := h.cache.Fetch(ctx, cacheKey, func() (string, error) {
		dao := ai_boilerplate_dao.Use(h.db).HelpCategory
		result, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.Eq(ID)).First()
		if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
			return "", err
		}
		marshal, err := h.encoding.Marshal(result)
		if err != nil {
			return "", err
		}
		return string(marshal), nil
	}, h.cache.TTL())
	if err != nil {
		return nil, err
	}
	if cacheValue != "" {
		err = h.encoding.Unmarshal([]byte(cacheValue), resp)
		if err != nil {
			return nil, err
		}
	}
	return resp, nil
}

// FindMultiByIDS 根据IDS查询多条数据
func (h *HelpCategoryRepo) FindMultiByIDS(ctx context.Context, IDS []string) ([]*ai_boilerplate_model.HelpCategory, error) {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	result, err := dao.WithContext(ctx).Where(dao.ID.In(IDS...)).Find()
	if err != nil {
		return nil, err
	}
	return result, nil
}

// FindMultiUnscopedByIDS 根据IDS查询多条数据（包括软删除）
func (h *HelpCategoryRepo) FindMultiUnscopedByIDS(ctx context.Context, IDS []string) ([]*ai_boilerplate_model.HelpCategory, error) {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.In(IDS...)).Find()
	if err != nil {
		return nil, err
	}
	return result, nil
}

// FindMultiCacheByIDS 根据IDS查询多条数据，并设置缓存
func (h *HelpCategoryRepo) FindMultiCacheByIDS(ctx context.Context, IDS []string) ([]*ai_boilerplate_model.HelpCategory, error) {
	resp := make([]*ai_boilerplate_model.HelpCategory, 0)
	cacheKeys := make([]string, 0)
	keyToParam := make(map[string]string)
	for _, item := range IDS {
		cacheKey := h.cache.Key(CacheHelpCategoryByIDPrefix, item)
		cacheKeys = append(cacheKeys, cacheKey)
		keyToParam[cacheKey] = item
	}
	cacheValue, err := h.cache.FetchBatch(ctx, cacheKeys, func(miss []string) (map[string]string, error) {
		dbValue := make(map[string]string)
		params := make([]string, 0)
		for _, item := range miss {
			dbValue[item] = ""
			params = append(params, keyToParam[item])
		}
		dao := ai_boilerplate_dao.Use(h.db).HelpCategory
		result, err := dao.WithContext(ctx).Where(dao.ID.In(params...)).Find()
		if err != nil {
			return nil, err
		}
		for _, item := range result {
			marshal, err := h.encoding.Marshal(item)
			if err != nil {
				return nil, err
			}
			dbValue[h.cache.Key(CacheHelpCategoryByIDPrefix, item.ID)] = string(marshal)
		}
		return dbValue, nil
	}, h.cache.TTL())
	if err != nil {
		return nil, err
	}
	for _, cacheKey := range cacheKeys {
		if cacheValue[cacheKey] != "" {
			tmp := new(ai_boilerplate_model.HelpCategory)
			err := h.encoding.Unmarshal([]byte(cacheValue[cacheKey]), tmp)
			if err != nil {
				return nil, err
			}
			resp = append(resp, tmp)
		}
	}
	return resp, nil
}

// FindMultiUnscopedCacheByIDS 根据IDS查询多条数据（包括软删除），并设置缓存
func (h *HelpCategoryRepo) FindMultiUnscopedCacheByIDS(ctx context.Context, IDS []string) ([]*ai_boilerplate_model.HelpCategory, error) {
	resp := make([]*ai_boilerplate_model.HelpCategory, 0)
	cacheKeys := make([]string, 0)
	keyToParam := make(map[string]string)
	for _, item := range IDS {
		cacheKey := h.cache.Key(CacheHelpCategoryUnscopedByIDPrefix, item)
		cacheKeys = append(cacheKeys, cacheKey)
		keyToParam[cacheKey] = item
	}
	cacheValue, err := h.cache.FetchBatch(ctx, cacheKeys, func(miss []string) (map[string]string, error) {
		dbValue := make(map[string]string)
		params := make([]string, 0)
		for _, item := range miss {
			dbValue[item] = ""
			params = append(params, keyToParam[item])
		}
		dao := ai_boilerplate_dao.Use(h.db).HelpCategory
		result, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.In(params...)).Find()
		if err != nil {
			return nil, err
		}
		for _, item := range result {
			marshal, err := h.encoding.Marshal(item)
			if err != nil {
				return nil, err
			}
			dbValue[h.cache.Key(CacheHelpCategoryUnscopedByIDPrefix, item.ID)] = string(marshal)
		}
		return dbValue, nil
	}, h.cache.TTL())
	if err != nil {
		return nil, err
	}
	for _, cacheKey := range cacheKeys {
		if cacheValue[cacheKey] != "" {
			tmp := new(ai_boilerplate_model.HelpCategory)
			err := h.encoding.Unmarshal([]byte(cacheValue[cacheKey]), tmp)
			if err != nil {
				return nil, err
			}
			resp = append(resp, tmp)
		}
	}
	return resp, nil
}

// FindMultiByOrder 根据order查询多条数据
func (h *HelpCategoryRepo) FindMultiByOrder(ctx context.Context, order int32) ([]*ai_boilerplate_model.HelpCategory, error) {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	result, err := dao.WithContext(ctx).Where(dao.Order.Eq(order)).Find()
	if err != nil {
		return nil, err
	}
	return result, nil
}

// FindMultiUnscopedByOrder 根据order查询多条数据（包括软删除）
func (h *HelpCategoryRepo) FindMultiUnscopedByOrder(ctx context.Context, order int32) ([]*ai_boilerplate_model.HelpCategory, error) {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.Order.Eq(order)).Find()
	if err != nil {
		return nil, err
	}
	return result, nil
}

// FindMultiCacheByOrder 根据order查询多条数据，并设置缓存
func (h *HelpCategoryRepo) FindMultiCacheByOrder(ctx context.Context, order int32) ([]*ai_boilerplate_model.HelpCategory, error) {
	resp := make([]*ai_boilerplate_model.HelpCategory, 0)
	cacheKey := h.cache.Key(CacheHelpCategoryByOrderPrefix, order)
	cacheValue, err := h.cache.Fetch(ctx, cacheKey, func() (string, error) {
		dao := ai_boilerplate_dao.Use(h.db).HelpCategory
		result, err := dao.WithContext(ctx).Where(dao.Order.Eq(order)).Find()
		if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
			return "", err
		}
		marshal, err := h.encoding.Marshal(result)
		if err != nil {
			return "", err
		}
		return string(marshal), nil
	}, h.cache.TTL())
	if err != nil {
		return nil, err
	}
	if cacheValue != "" {
		err = h.encoding.Unmarshal([]byte(cacheValue), &resp)
		if err != nil {
			return nil, err
		}
	}
	return resp, nil
}

// FindMultiUnscopedCacheByOrder 根据order查询多条数据（包括软删除），并设置缓存
func (h *HelpCategoryRepo) FindMultiUnscopedCacheByOrder(ctx context.Context, order int32) ([]*ai_boilerplate_model.HelpCategory, error) {
	resp := make([]*ai_boilerplate_model.HelpCategory, 0)
	cacheKey := h.cache.Key(CacheHelpCategoryUnscopedByOrderPrefix, order)
	cacheValue, err := h.cache.Fetch(ctx, cacheKey, func() (string, error) {
		dao := ai_boilerplate_dao.Use(h.db).HelpCategory
		result, err := dao.WithContext(ctx).Unscoped().Where(dao.Order.Eq(order)).Find()
		if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
			return "", err
		}
		marshal, err := h.encoding.Marshal(result)
		if err != nil {
			return "", err
		}
		return string(marshal), nil
	}, h.cache.TTL())
	if err != nil {
		return nil, err
	}
	if cacheValue != "" {
		err = h.encoding.Unmarshal([]byte(cacheValue), &resp)
		if err != nil {
			return nil, err
		}
	}
	return resp, nil
}

// FindMultiByOrders 根据orders查询多条数据
func (h *HelpCategoryRepo) FindMultiByOrders(ctx context.Context, orders []int32) ([]*ai_boilerplate_model.HelpCategory, error) {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	result, err := dao.WithContext(ctx).Where(dao.Order.In(orders...)).Find()
	if err != nil {
		return nil, err
	}
	return result, nil
}

// FindMultiUnscopedByOrders 根据orders查询多条数据（包括软删除）
func (h *HelpCategoryRepo) FindMultiUnscopedByOrders(ctx context.Context, orders []int32) ([]*ai_boilerplate_model.HelpCategory, error) {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.Order.In(orders...)).Find()
	if err != nil {
		return nil, err
	}
	return result, nil
}

// FindMultiCacheByOrders 根据orders查询多条数据，并设置缓存
func (h *HelpCategoryRepo) FindMultiCacheByOrders(ctx context.Context, orders []int32) ([]*ai_boilerplate_model.HelpCategory, error) {
	resp := make([]*ai_boilerplate_model.HelpCategory, 0)
	cacheKeys := make([]string, 0)
	keyToParam := make(map[string]int32)
	for _, item := range orders {
		cacheKey := h.cache.Key(CacheHelpCategoryByOrderPrefix, item)
		cacheKeys = append(cacheKeys, cacheKey)
		keyToParam[cacheKey] = item
	}
	cacheValue, err := h.cache.FetchBatch(ctx, cacheKeys, func(miss []string) (map[string]string, error) {
		dbValue := make(map[string]string)
		params := make([]int32, 0)
		for _, item := range miss {
			dbValue[item] = ""
			params = append(params, keyToParam[item])
		}
		dao := ai_boilerplate_dao.Use(h.db).HelpCategory
		result, err := dao.WithContext(ctx).Where(dao.Order.In(params...)).Find()
		if err != nil {
			return nil, err
		}
		keyToValues := make(map[string][]*ai_boilerplate_model.HelpCategory)
		for _, item := range result {
			key := h.cache.Key(CacheHelpCategoryByOrderPrefix, item.Order)
			if keyToValues[key] == nil {
				keyToValues[key] = make([]*ai_boilerplate_model.HelpCategory, 0)
			}
			keyToValues[key] = append(keyToValues[key], item)
		}
		for item := range dbValue {
			if keyToValues[item] != nil {
				marshal, err := h.encoding.Marshal(keyToValues[item])
				if err != nil {
					return nil, err
				}
				dbValue[item] = string(marshal)
			}
		}
		return dbValue, nil
	}, h.cache.TTL())
	if err != nil {
		return nil, err
	}
	for _, cacheKey := range cacheKeys {
		if cacheValue[cacheKey] != "" {
			tmp := make([]*ai_boilerplate_model.HelpCategory, 0)
			err := h.encoding.Unmarshal([]byte(cacheValue[cacheKey]), &tmp)
			if err != nil {
				return nil, err
			}
			resp = append(resp, tmp...)
		}
	}
	return resp, nil
}

// FindMultiUnscopedCacheByOrders 根据orders查询多条数据（包括软删除），并设置缓存
func (h *HelpCategoryRepo) FindMultiUnscopedCacheByOrders(ctx context.Context, orders []int32) ([]*ai_boilerplate_model.HelpCategory, error) {
	resp := make([]*ai_boilerplate_model.HelpCategory, 0)
	cacheKeys := make([]string, 0)
	keyToParam := make(map[string]int32)
	for _, item := range orders {
		cacheKey := h.cache.Key(CacheHelpCategoryUnscopedByOrderPrefix, item)
		cacheKeys = append(cacheKeys, cacheKey)
		keyToParam[cacheKey] = item
	}
	cacheValue, err := h.cache.FetchBatch(ctx, cacheKeys, func(miss []string) (map[string]string, error) {
		dbValue := make(map[string]string)
		params := make([]int32, 0)
		for _, item := range miss {
			dbValue[item] = ""
			params = append(params, keyToParam[item])
		}
		dao := ai_boilerplate_dao.Use(h.db).HelpCategory
		result, err := dao.WithContext(ctx).Unscoped().Where(dao.Order.In(params...)).Find()
		if err != nil {
			return nil, err
		}
		keyToValues := make(map[string][]*ai_boilerplate_model.HelpCategory)
		for _, item := range result {
			key := h.cache.Key(CacheHelpCategoryUnscopedByOrderPrefix, item.Order)
			if keyToValues[key] == nil {
				keyToValues[key] = make([]*ai_boilerplate_model.HelpCategory, 0)
			}
			keyToValues[key] = append(keyToValues[key], item)
		}
		for item := range dbValue {
			if keyToValues[item] != nil {
				marshal, err := h.encoding.Marshal(keyToValues[item])
				if err != nil {
					return nil, err
				}
				dbValue[item] = string(marshal)
			}
		}
		return dbValue, nil
	}, h.cache.TTL())
	if err != nil {
		return nil, err
	}
	for _, cacheKey := range cacheKeys {
		if cacheValue[cacheKey] != "" {
			tmp := make([]*ai_boilerplate_model.HelpCategory, 0)
			err := h.encoding.Unmarshal([]byte(cacheValue[cacheKey]), &tmp)
			if err != nil {
				return nil, err
			}
			resp = append(resp, tmp...)
		}
	}
	return resp, nil
}

// FindMultiByCondition 自定义查询数据(通用)
// 非万能查询方法,请评估后谨慎使用
func (h *HelpCategoryRepo) FindMultiByCondition(ctx context.Context, conditionReq *condition.Req) ([]*ai_boilerplate_model.HelpCategory, *condition.Reply, error) {
	result := make([]*ai_boilerplate_model.HelpCategory, 0)
	conditionReply := &condition.Reply{}
	var total int64
	whereExpressions, orderExpressions, err := conditionReq.ConvertToGormExpression(ai_boilerplate_model.HelpCategory{})
	if err != nil {
		return result, conditionReply, err
	}
	if conditionReq.Page != 0 && conditionReq.PageSize != 0 {
		err = h.db.WithContext(ctx).Model(&ai_boilerplate_model.HelpCategory{}).Clauses(whereExpressions...).Count(&total).Error
		if err != nil {
			return result, conditionReply, err
		}
		if total == 0 {
			return result, conditionReply, nil
		}
		conditionReply, err = conditionReq.ConvertToPage(int32(total))
		if err != nil {
			return result, conditionReply, err
		}
		query := h.db.WithContext(ctx).Model(&ai_boilerplate_model.HelpCategory{}).Clauses(whereExpressions...).Clauses(orderExpressions...)
		if conditionReply.Page != 0 && conditionReply.PageSize != 0 {
			query = query.Offset(int((conditionReply.Page - 1) * conditionReply.PageSize))
			query = query.Limit(int(conditionReply.PageSize))
		}
		err = query.Find(&result).Error
		if err != nil {
			return result, conditionReply, err
		}
	} else {
		err = h.db.WithContext(ctx).Model(&ai_boilerplate_model.HelpCategory{}).Clauses(whereExpressions...).Clauses(orderExpressions...).Find(&result).Error
		if err != nil {
			return result, conditionReply, err
		}
		conditionReply.Total = int32(len(result))
	}
	return result, conditionReply, err
}

// FindMultiUnscopedByCondition 自定义查询数据(通用)（包括软删除）
// 非万能查询方法,请评估后谨慎使用
func (h *HelpCategoryRepo) FindMultiUnscopedByCondition(ctx context.Context, conditionReq *condition.Req) ([]*ai_boilerplate_model.HelpCategory, *condition.Reply, error) {
	result := make([]*ai_boilerplate_model.HelpCategory, 0)
	conditionReply := &condition.Reply{}
	var total int64
	whereExpressions, orderExpressions, err := conditionReq.ConvertToGormExpression(ai_boilerplate_model.HelpCategory{})
	if err != nil {
		return result, conditionReply, err
	}
	if conditionReq.Page != 0 && conditionReq.PageSize != 0 {
		err = h.db.WithContext(ctx).Model(&ai_boilerplate_model.HelpCategory{}).Unscoped().Clauses(whereExpressions...).Count(&total).Error
		if err != nil {
			return result, conditionReply, err
		}
		if total == 0 {
			return result, conditionReply, nil
		}
		conditionReply, err = conditionReq.ConvertToPage(int32(total))
		if err != nil {
			return result, conditionReply, err
		}
		query := h.db.WithContext(ctx).Model(&ai_boilerplate_model.HelpCategory{}).Unscoped().Clauses(whereExpressions...).Clauses(orderExpressions...)
		if conditionReply.Page != 0 && conditionReply.PageSize != 0 {
			query = query.Offset(int((conditionReply.Page - 1) * conditionReply.PageSize))
			query = query.Limit(int(conditionReply.PageSize))
		}
		err = query.Find(&result).Error
		if err != nil {
			return result, conditionReply, err
		}
	} else {
		err = h.db.WithContext(ctx).Model(&ai_boilerplate_model.HelpCategory{}).Unscoped().Clauses(whereExpressions...).Clauses(orderExpressions...).Find(&result).Error
		if err != nil {
			return result, conditionReply, err
		}
		conditionReply.Total = int32(len(result))
	}
	return result, conditionReply, err
}

// FindMultiCacheByCondition 自定义查询数据(通用),并设置缓存
// 非万能查询方法,缓存命中率低,请评估后谨慎使用
func (h *HelpCategoryRepo) FindMultiCacheByCondition(ctx context.Context, conditionReq *condition.Req) ([]*ai_boilerplate_model.HelpCategory, *condition.Reply, error) {
	type Tmp struct {
		Result         []*ai_boilerplate_model.HelpCategory
		ConditionReply *condition.Reply
	}
	tmp := Tmp{
		Result:         make([]*ai_boilerplate_model.HelpCategory, 0),
		ConditionReply: &condition.Reply{},
	}
	cacheKey := h.cache.Key(CacheHelpCategoryByConditionPrefix)
	cacheField := conditionReq.ConvertToCacheField()
	cacheValue, err := h.cache.FetchHash(ctx, cacheKey, cacheField, func() (string, error) {
		result, conditionReply, err := h.FindMultiByCondition(ctx, conditionReq)
		if err != nil {
			return "", err
		}
		tmp.Result = result
		tmp.ConditionReply = conditionReply
		marshal, err := h.encoding.Marshal(tmp)
		if err != nil {
			return "", err
		}
		return string(marshal), nil
	}, h.cache.TTL())
	if err != nil {
		return tmp.Result, tmp.ConditionReply, err
	}
	if cacheValue != "" {
		err = h.encoding.Unmarshal([]byte(cacheValue), &tmp)
		if err != nil {
			return tmp.Result, tmp.ConditionReply, err
		}
	}
	return tmp.Result, tmp.ConditionReply, nil
}

// FindMultiUnscopedCacheByCondition 自定义查询数据(通用)（包括软删除）,并设置缓存
// 非万能查询方法,缓存命中率低,请评估后谨慎使用
func (h *HelpCategoryRepo) FindMultiUnscopedCacheByCondition(ctx context.Context, conditionReq *condition.Req) ([]*ai_boilerplate_model.HelpCategory, *condition.Reply, error) {
	type Tmp struct {
		Result         []*ai_boilerplate_model.HelpCategory
		ConditionReply *condition.Reply
	}
	tmp := Tmp{
		Result:         make([]*ai_boilerplate_model.HelpCategory, 0),
		ConditionReply: &condition.Reply{},
	}
	cacheKey := h.cache.Key(CacheHelpCategoryUnscopedByConditionPrefix)
	cacheField := conditionReq.ConvertToCacheField()
	cacheValue, err := h.cache.FetchHash(ctx, cacheKey, cacheField, func() (string, error) {
		result, conditionReply, err := h.FindMultiUnscopedByCondition(ctx, conditionReq)
		if err != nil {
			return "", err
		}
		tmp.Result = result
		tmp.ConditionReply = conditionReply
		marshal, err := h.encoding.Marshal(tmp)
		if err != nil {
			return "", err
		}
		return string(marshal), nil
	}, h.cache.TTL())
	if err != nil {
		return tmp.Result, tmp.ConditionReply, err
	}
	if cacheValue != "" {
		err = h.encoding.Unmarshal([]byte(cacheValue), &tmp)
		if err != nil {
			return tmp.Result, tmp.ConditionReply, err
		}
	}
	return tmp.Result, tmp.ConditionReply, nil
}

// DeleteOneByID 根据ID删除一条数据
func (h *HelpCategoryRepo) DeleteOneByID(ctx context.Context, ID string) error {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	_, err := dao.WithContext(ctx).Where(dao.ID.Eq(ID)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteOneUnscopedByID 根据ID删除一条数据
func (h *HelpCategoryRepo) DeleteOneUnscopedByID(ctx context.Context, ID string) error {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.Eq(ID)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteOneCacheByID 根据ID删除一条数据，并删除缓存
func (h *HelpCategoryRepo) DeleteOneCacheByID(ctx context.Context, ID string) error {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	result, err := dao.WithContext(ctx).Where(dao.ID.Eq(ID)).First()
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return err
	}
	if result == nil {
		return nil
	}
	_, err = dao.WithContext(ctx).Where(dao.ID.Eq(ID)).Delete()
	if err != nil {
		return err
	}
	err = h.DeleteIndexCache(ctx, result)
	if err != nil {
		return err
	}
	return nil
}

// DeleteOneUnscopedCacheByID 根据ID删除一条数据，并删除缓存
func (h *HelpCategoryRepo) DeleteOneUnscopedCacheByID(ctx context.Context, ID string) error {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.Eq(ID)).First()
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return err
	}
	if result == nil {
		return nil
	}
	_, err = dao.WithContext(ctx).Unscoped().Where(dao.ID.Eq(ID)).Delete()
	if err != nil {
		return err
	}
	err = h.DeleteIndexCache(ctx, result)
	if err != nil {
		return err
	}
	return nil
}

// DeleteOneByIDTx 根据ID删除一条数据
func (h *HelpCategoryRepo) DeleteOneByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string) error {
	dao := tx.HelpCategory
	_, err := dao.WithContext(ctx).Where(dao.ID.Eq(ID)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteOneUnscopedByIDTx 根据ID删除一条数据
func (h *HelpCategoryRepo) DeleteOneUnscopedByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string) error {
	dao := tx.HelpCategory
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.Eq(ID)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteOneCacheByIDTx 根据ID删除一条数据，并删除缓存
func (h *HelpCategoryRepo) DeleteOneCacheByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string) error {
	dao := tx.HelpCategory
	result, err := dao.WithContext(ctx).Where(dao.ID.Eq(ID)).First()
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return err
	}
	if result == nil {
		return nil
	}
	_, err = dao.WithContext(ctx).Where(dao.ID.Eq(ID)).Delete()
	if err != nil {
		return err
	}
	err = h.DeleteIndexCache(ctx, result)
	if err != nil {
		return err
	}
	return nil
}

// DeleteOneUnscopedCacheByIDTx 根据ID删除一条数据，并删除缓存
func (h *HelpCategoryRepo) DeleteOneUnscopedCacheByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string) error {
	dao := tx.HelpCategory
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.Eq(ID)).First()
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return err
	}
	if result == nil {
		return nil
	}
	_, err = dao.WithContext(ctx).Unscoped().Where(dao.ID.Eq(ID)).Delete()
	if err != nil {
		return err
	}
	err = h.DeleteIndexCache(ctx, result)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiByIDS 根据IDS删除多条数据
func (h *HelpCategoryRepo) DeleteMultiByIDS(ctx context.Context, IDS []string) error {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	_, err := dao.WithContext(ctx).Where(dao.ID.In(IDS...)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedByIDS 根据IDS删除多条数据
func (h *HelpCategoryRepo) DeleteMultiUnscopedByIDS(ctx context.Context, IDS []string) error {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.In(IDS...)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiCacheByIDS 根据IDS删除多条数据，并删除缓存
func (h *HelpCategoryRepo) DeleteMultiCacheByIDS(ctx context.Context, IDS []string) error {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	result, err := dao.WithContext(ctx).Where(dao.ID.In(IDS...)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Where(dao.ID.In(IDS...)).Delete()
	if err != nil {
		return err
	}
	err = h.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedCacheByIDS 根据IDS删除多条数据，并删除缓存
func (h *HelpCategoryRepo) DeleteMultiUnscopedCacheByIDS(ctx context.Context, IDS []string) error {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.In(IDS...)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Unscoped().Where(dao.ID.In(IDS...)).Delete()
	if err != nil {
		return err
	}
	err = h.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiByIDSTx 根据IDS删除多条数据
func (h *HelpCategoryRepo) DeleteMultiByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string) error {
	dao := tx.HelpCategory
	_, err := dao.WithContext(ctx).Where(dao.ID.In(IDS...)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedByIDSTx 根据IDS删除多条数据
func (h *HelpCategoryRepo) DeleteMultiUnscopedByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string) error {
	dao := tx.HelpCategory
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.In(IDS...)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiCacheByIDSTx 根据IDS删除多条数据，并删除缓存
func (h *HelpCategoryRepo) DeleteMultiCacheByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string) error {
	dao := tx.HelpCategory
	result, err := dao.WithContext(ctx).Where(dao.ID.In(IDS...)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Where(dao.ID.In(IDS...)).Delete()
	if err != nil {
		return err
	}
	err = h.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedCacheByIDSTx 根据IDS删除多条数据，并删除缓存
func (h *HelpCategoryRepo) DeleteMultiUnscopedCacheByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string) error {
	dao := tx.HelpCategory
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.In(IDS...)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Unscoped().Where(dao.ID.In(IDS...)).Delete()
	if err != nil {
		return err
	}
	err = h.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiByOrder 根据Order删除多条数据
func (h *HelpCategoryRepo) DeleteMultiByOrder(ctx context.Context, order int32) error {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	_, err := dao.WithContext(ctx).Where(dao.Order.Eq(order)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedByOrder 根据Order删除多条数据
func (h *HelpCategoryRepo) DeleteMultiUnscopedByOrder(ctx context.Context, order int32) error {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.Order.Eq(order)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiCacheByOrder 根据order删除多条数据，并删除缓存
func (h *HelpCategoryRepo) DeleteMultiCacheByOrder(ctx context.Context, order int32) error {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	result, err := dao.WithContext(ctx).Where(dao.Order.Eq(order)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Where(dao.Order.Eq(order)).Delete()
	if err != nil {
		return err
	}
	err = h.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedCacheByOrder 根据order删除多条数据，并删除缓存
func (h *HelpCategoryRepo) DeleteMultiUnscopedCacheByOrder(ctx context.Context, order int32) error {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.Order.Eq(order)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Unscoped().Where(dao.Order.Eq(order)).Delete()
	if err != nil {
		return err
	}
	err = h.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiByOrderTx 根据order删除多条数据
func (h *HelpCategoryRepo) DeleteMultiByOrderTx(ctx context.Context, tx *ai_boilerplate_dao.Query, order int32) error {
	dao := tx.HelpCategory
	_, err := dao.WithContext(ctx).Where(dao.Order.Eq(order)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedByOrderTx 根据order删除多条数据
func (h *HelpCategoryRepo) DeleteMultiUnscopedByOrderTx(ctx context.Context, tx *ai_boilerplate_dao.Query, order int32) error {
	dao := tx.HelpCategory
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.Order.Eq(order)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiCacheByOrderTx 根据order删除多条数据，并删除缓存
func (h *HelpCategoryRepo) DeleteMultiCacheByOrderTx(ctx context.Context, tx *ai_boilerplate_dao.Query, order int32) error {
	dao := tx.HelpCategory
	result, err := dao.WithContext(ctx).Where(dao.Order.Eq(order)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Where(dao.Order.Eq(order)).Delete()
	if err != nil {
		return err
	}
	err = h.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedCacheByOrderTx 根据order删除多条数据，并删除缓存
func (h *HelpCategoryRepo) DeleteMultiUnscopedCacheByOrderTx(ctx context.Context, tx *ai_boilerplate_dao.Query, order int32) error {
	dao := tx.HelpCategory
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.Order.Eq(order)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Unscoped().Where(dao.Order.Eq(order)).Delete()
	if err != nil {
		return err
	}
	err = h.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiByOrders 根据orders删除多条数据
func (h *HelpCategoryRepo) DeleteMultiByOrders(ctx context.Context, orders []int32) error {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	_, err := dao.WithContext(ctx).Where(dao.Order.In(orders...)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedByOrders 根据orders删除多条数据
func (h *HelpCategoryRepo) DeleteMultiUnscopedByOrders(ctx context.Context, orders []int32) error {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.Order.In(orders...)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiCacheByOrders 根据orders删除多条数据，并删除缓存
func (h *HelpCategoryRepo) DeleteMultiCacheByOrders(ctx context.Context, orders []int32) error {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	result, err := dao.WithContext(ctx).Where(dao.Order.In(orders...)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Where(dao.Order.In(orders...)).Delete()
	if err != nil {
		return err
	}
	err = h.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedCacheByOrders 根据orders删除多条数据，并删除缓存
func (h *HelpCategoryRepo) DeleteMultiUnscopedCacheByOrders(ctx context.Context, orders []int32) error {
	dao := ai_boilerplate_dao.Use(h.db).HelpCategory
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.Order.In(orders...)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Unscoped().Where(dao.Order.In(orders...)).Delete()
	if err != nil {
		return err
	}
	err = h.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiByOrdersTx 根据orders删除多条数据
func (h *HelpCategoryRepo) DeleteMultiByOrdersTx(ctx context.Context, tx *ai_boilerplate_dao.Query, orders []int32) error {
	dao := tx.HelpCategory
	_, err := dao.WithContext(ctx).Where(dao.Order.In(orders...)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedByOrdersTx 根据orders删除多条数据
func (h *HelpCategoryRepo) DeleteMultiUnscopedByOrdersTx(ctx context.Context, tx *ai_boilerplate_dao.Query, orders []int32) error {
	dao := tx.HelpCategory
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.Order.In(orders...)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiCacheByOrdersTx 根据orders删除多条数据，并删除缓存
func (h *HelpCategoryRepo) DeleteMultiCacheByOrdersTx(ctx context.Context, tx *ai_boilerplate_dao.Query, orders []int32) error {
	dao := tx.HelpCategory
	result, err := dao.WithContext(ctx).Where(dao.Order.In(orders...)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Where(dao.Order.In(orders...)).Delete()
	if err != nil {
		return err
	}
	err = h.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedCacheByOrdersTx 根据orders删除多条数据，并删除缓存
func (h *HelpCategoryRepo) DeleteMultiUnscopedCacheByOrdersTx(ctx context.Context, tx *ai_boilerplate_dao.Query, orders []int32) error {
	dao := tx.HelpCategory
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.Order.In(orders...)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Unscoped().Where(dao.Order.In(orders...)).Delete()
	if err != nil {
		return err
	}
	err = h.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteUniqueIndexCache 删除索引存在的缓存
func (h *HelpCategoryRepo) DeleteIndexCache(ctx context.Context, data ...*ai_boilerplate_model.HelpCategory) error {
	KeyMap := make(map[string]struct{})
	keys := make([]string, 0)
	keys = append(keys, h.cache.Key(CacheHelpCategoryByConditionPrefix))
	keys = append(keys, h.cache.Key(CacheHelpCategoryUnscopedByConditionPrefix))
	for _, item := range data {
		if item != nil {
			KeyMap[h.cache.Key(CacheHelpCategoryByIDPrefix, item.ID)] = struct{}{}
			KeyMap[h.cache.Key(CacheHelpCategoryUnscopedByIDPrefix, item.ID)] = struct{}{}
			KeyMap[h.cache.Key(CacheHelpCategoryByOrderPrefix, item.Order)] = struct{}{}
			KeyMap[h.cache.Key(CacheHelpCategoryUnscopedByOrderPrefix, item.Order)] = struct{}{}
		}
	}
	for item := range KeyMap {
		keys = append(keys, item)
	}
	err := h.cache.DelBatch(ctx, keys)
	if err != nil {
		return err
	}
	return nil
}
