// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package ai_boilerplate_model

import (
	"database/sql"
	"time"

	"gorm.io/gorm"
)

const TableNameBanner = "banner"

// Banner mapped from table <banner>
type Banner struct {
	ID        string         `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid();comment:id" json:"id"`          // id
	TenantID  string         `gorm:"column:tenant_id;type:character varying(64);not null;comment:租户id" json:"tenantId"`      // 租户id
	Title     string         `gorm:"column:title;type:character varying(200);not null;comment:标题" json:"title"`              // 标题
	ImageURL  string         `gorm:"column:image_url;type:character varying(500);not null;comment:图片URL" json:"imageUrl"`    // 图片URL
	LinkURL   string         `gorm:"column:link_url;type:character varying(500);not null;comment:跳转链接" json:"linkUrl"`       // 跳转链接
	LinkType  string         `gorm:"column:link_type;type:character varying(32);not null;comment:跳转类型" json:"linkType"`      // 跳转类型
	Position  string         `gorm:"column:position;type:character varying(64);not null;comment:展示位置" json:"position"`       // 展示位置
	Platform  string         `gorm:"column:platform;type:character varying(32);not null;comment:平台" json:"platform"`         // 平台
	Sort      int32          `gorm:"column:sort;type:integer;not null;comment:排序" json:"sort"`                               // 排序
	Status    int16          `gorm:"column:status;type:smallint;not null;comment:状态(-1禁用,1开启)" json:"status"`                // 状态(-1禁用,1开启)
	StartTime sql.NullTime   `gorm:"column:start_time;type:timestamp with time zone;comment:开始时间" json:"startTime"`          // 开始时间
	EndTime   sql.NullTime   `gorm:"column:end_time;type:timestamp with time zone;comment:结束时间" json:"endTime"`              // 结束时间
	CreatedAt time.Time      `gorm:"column:created_at;type:timestamp with time zone;not null;comment:创建时间" json:"createdAt"` // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;type:timestamp with time zone;not null;comment:更新时间" json:"updatedAt"` // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone;comment:删除时间" json:"deletedAt"`          // 删除时间
}

// TableName Banner's table name
func (*Banner) TableName() string {
	return TableNameBanner
}
