// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: admin/v1/banner.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on BannerInfo with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *BannerInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BannerInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in BannerInfoMultiError, or
// nil if none found.
func (m *BannerInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *BannerInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for TenantId

	// no validation rules for Title

	// no validation rules for ImageURL

	// no validation rules for LinkURL

	// no validation rules for LinkType

	// no validation rules for Position

	// no validation rules for Platform

	// no validation rules for Sort

	// no validation rules for Status

	// no validation rules for StartTime

	// no validation rules for EndTime

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return BannerInfoMultiError(errors)
	}

	return nil
}

// BannerInfoMultiError is an error wrapping multiple validation errors
// returned by BannerInfo.ValidateAll() if the designated constraints aren't met.
type BannerInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BannerInfoMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BannerInfoMultiError) AllErrors() []error { return m }

// BannerInfoValidationError is the validation error returned by
// BannerInfo.Validate if the designated constraints aren't met.
type BannerInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BannerInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BannerInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BannerInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BannerInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BannerInfoValidationError) ErrorName() string { return "BannerInfoValidationError" }

// Error satisfies the builtin error interface
func (e BannerInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBannerInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BannerInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BannerInfoValidationError{}

// Validate checks the field values on CreateBannerReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CreateBannerReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateBannerReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateBannerReqMultiError, or nil if none found.
func (m *CreateBannerReq) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateBannerReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TenantId

	// no validation rules for Title

	// no validation rules for ImageURL

	// no validation rules for LinkURL

	// no validation rules for LinkType

	// no validation rules for Position

	// no validation rules for Platform

	// no validation rules for Sort

	// no validation rules for Status

	// no validation rules for StartTime

	// no validation rules for EndTime

	if len(errors) > 0 {
		return CreateBannerReqMultiError(errors)
	}

	return nil
}

// CreateBannerReqMultiError is an error wrapping multiple validation errors
// returned by CreateBannerReq.ValidateAll() if the designated constraints
// aren't met.
type CreateBannerReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateBannerReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateBannerReqMultiError) AllErrors() []error { return m }

// CreateBannerReqValidationError is the validation error returned by
// CreateBannerReq.Validate if the designated constraints aren't met.
type CreateBannerReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateBannerReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateBannerReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateBannerReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateBannerReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateBannerReqValidationError) ErrorName() string { return "CreateBannerReqValidationError" }

// Error satisfies the builtin error interface
func (e CreateBannerReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateBannerReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateBannerReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateBannerReqValidationError{}

// Validate checks the field values on CreateBannerReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CreateBannerReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateBannerReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateBannerReplyMultiError, or nil if none found.
func (m *CreateBannerReply) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateBannerReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return CreateBannerReplyMultiError(errors)
	}

	return nil
}

// CreateBannerReplyMultiError is an error wrapping multiple validation errors
// returned by CreateBannerReply.ValidateAll() if the designated constraints
// aren't met.
type CreateBannerReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateBannerReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateBannerReplyMultiError) AllErrors() []error { return m }

// CreateBannerReplyValidationError is the validation error returned by
// CreateBannerReply.Validate if the designated constraints aren't met.
type CreateBannerReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateBannerReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateBannerReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateBannerReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateBannerReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateBannerReplyValidationError) ErrorName() string {
	return "CreateBannerReplyValidationError"
}

// Error satisfies the builtin error interface
func (e CreateBannerReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateBannerReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateBannerReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateBannerReplyValidationError{}

// Validate checks the field values on UpdateBannerReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UpdateBannerReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateBannerReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateBannerReqMultiError, or nil if none found.
func (m *UpdateBannerReq) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateBannerReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for TenantId

	// no validation rules for Title

	// no validation rules for ImageURL

	// no validation rules for LinkURL

	// no validation rules for LinkType

	// no validation rules for Position

	// no validation rules for Platform

	// no validation rules for Sort

	// no validation rules for Status

	// no validation rules for StartTime

	// no validation rules for EndTime

	if len(errors) > 0 {
		return UpdateBannerReqMultiError(errors)
	}

	return nil
}

// UpdateBannerReqMultiError is an error wrapping multiple validation errors
// returned by UpdateBannerReq.ValidateAll() if the designated constraints
// aren't met.
type UpdateBannerReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateBannerReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateBannerReqMultiError) AllErrors() []error { return m }

// UpdateBannerReqValidationError is the validation error returned by
// UpdateBannerReq.Validate if the designated constraints aren't met.
type UpdateBannerReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateBannerReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateBannerReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateBannerReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateBannerReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateBannerReqValidationError) ErrorName() string { return "UpdateBannerReqValidationError" }

// Error satisfies the builtin error interface
func (e UpdateBannerReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateBannerReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateBannerReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateBannerReqValidationError{}

// Validate checks the field values on UpdateBannerReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UpdateBannerReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateBannerReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateBannerReplyMultiError, or nil if none found.
func (m *UpdateBannerReply) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateBannerReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return UpdateBannerReplyMultiError(errors)
	}

	return nil
}

// UpdateBannerReplyMultiError is an error wrapping multiple validation errors
// returned by UpdateBannerReply.ValidateAll() if the designated constraints
// aren't met.
type UpdateBannerReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateBannerReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateBannerReplyMultiError) AllErrors() []error { return m }

// UpdateBannerReplyValidationError is the validation error returned by
// UpdateBannerReply.Validate if the designated constraints aren't met.
type UpdateBannerReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateBannerReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateBannerReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateBannerReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateBannerReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateBannerReplyValidationError) ErrorName() string {
	return "UpdateBannerReplyValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateBannerReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateBannerReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateBannerReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateBannerReplyValidationError{}

// Validate checks the field values on UpdateBannerStatusReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateBannerStatusReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateBannerStatusReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateBannerStatusReqMultiError, or nil if none found.
func (m *UpdateBannerStatusReq) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateBannerStatusReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Status

	if len(errors) > 0 {
		return UpdateBannerStatusReqMultiError(errors)
	}

	return nil
}

// UpdateBannerStatusReqMultiError is an error wrapping multiple validation
// errors returned by UpdateBannerStatusReq.ValidateAll() if the designated
// constraints aren't met.
type UpdateBannerStatusReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateBannerStatusReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateBannerStatusReqMultiError) AllErrors() []error { return m }

// UpdateBannerStatusReqValidationError is the validation error returned by
// UpdateBannerStatusReq.Validate if the designated constraints aren't met.
type UpdateBannerStatusReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateBannerStatusReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateBannerStatusReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateBannerStatusReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateBannerStatusReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateBannerStatusReqValidationError) ErrorName() string {
	return "UpdateBannerStatusReqValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateBannerStatusReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateBannerStatusReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateBannerStatusReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateBannerStatusReqValidationError{}

// Validate checks the field values on UpdateBannerStatusReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateBannerStatusReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateBannerStatusReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateBannerStatusReplyMultiError, or nil if none found.
func (m *UpdateBannerStatusReply) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateBannerStatusReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return UpdateBannerStatusReplyMultiError(errors)
	}

	return nil
}

// UpdateBannerStatusReplyMultiError is an error wrapping multiple validation
// errors returned by UpdateBannerStatusReply.ValidateAll() if the designated
// constraints aren't met.
type UpdateBannerStatusReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateBannerStatusReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateBannerStatusReplyMultiError) AllErrors() []error { return m }

// UpdateBannerStatusReplyValidationError is the validation error returned by
// UpdateBannerStatusReply.Validate if the designated constraints aren't met.
type UpdateBannerStatusReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateBannerStatusReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateBannerStatusReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateBannerStatusReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateBannerStatusReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateBannerStatusReplyValidationError) ErrorName() string {
	return "UpdateBannerStatusReplyValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateBannerStatusReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateBannerStatusReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateBannerStatusReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateBannerStatusReplyValidationError{}

// Validate checks the field values on DeleteBannerReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DeleteBannerReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteBannerReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteBannerReqMultiError, or nil if none found.
func (m *DeleteBannerReq) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteBannerReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return DeleteBannerReqMultiError(errors)
	}

	return nil
}

// DeleteBannerReqMultiError is an error wrapping multiple validation errors
// returned by DeleteBannerReq.ValidateAll() if the designated constraints
// aren't met.
type DeleteBannerReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteBannerReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteBannerReqMultiError) AllErrors() []error { return m }

// DeleteBannerReqValidationError is the validation error returned by
// DeleteBannerReq.Validate if the designated constraints aren't met.
type DeleteBannerReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteBannerReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteBannerReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteBannerReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteBannerReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteBannerReqValidationError) ErrorName() string { return "DeleteBannerReqValidationError" }

// Error satisfies the builtin error interface
func (e DeleteBannerReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteBannerReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteBannerReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteBannerReqValidationError{}

// Validate checks the field values on DeleteBannerReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DeleteBannerReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteBannerReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteBannerReplyMultiError, or nil if none found.
func (m *DeleteBannerReply) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteBannerReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteBannerReplyMultiError(errors)
	}

	return nil
}

// DeleteBannerReplyMultiError is an error wrapping multiple validation errors
// returned by DeleteBannerReply.ValidateAll() if the designated constraints
// aren't met.
type DeleteBannerReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteBannerReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteBannerReplyMultiError) AllErrors() []error { return m }

// DeleteBannerReplyValidationError is the validation error returned by
// DeleteBannerReply.Validate if the designated constraints aren't met.
type DeleteBannerReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteBannerReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteBannerReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteBannerReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteBannerReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteBannerReplyValidationError) ErrorName() string {
	return "DeleteBannerReplyValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteBannerReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteBannerReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteBannerReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteBannerReplyValidationError{}

// Validate checks the field values on GetBannerInfoReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetBannerInfoReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetBannerInfoReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetBannerInfoReqMultiError, or nil if none found.
func (m *GetBannerInfoReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetBannerInfoReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return GetBannerInfoReqMultiError(errors)
	}

	return nil
}

// GetBannerInfoReqMultiError is an error wrapping multiple validation errors
// returned by GetBannerInfoReq.ValidateAll() if the designated constraints
// aren't met.
type GetBannerInfoReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetBannerInfoReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetBannerInfoReqMultiError) AllErrors() []error { return m }

// GetBannerInfoReqValidationError is the validation error returned by
// GetBannerInfoReq.Validate if the designated constraints aren't met.
type GetBannerInfoReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetBannerInfoReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetBannerInfoReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetBannerInfoReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetBannerInfoReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetBannerInfoReqValidationError) ErrorName() string { return "GetBannerInfoReqValidationError" }

// Error satisfies the builtin error interface
func (e GetBannerInfoReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetBannerInfoReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetBannerInfoReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetBannerInfoReqValidationError{}

// Validate checks the field values on GetBannerInfoReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetBannerInfoReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetBannerInfoReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetBannerInfoReplyMultiError, or nil if none found.
func (m *GetBannerInfoReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetBannerInfoReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetBannerInfoReplyValidationError{
					field:  "Info",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetBannerInfoReplyValidationError{
					field:  "Info",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetBannerInfoReplyValidationError{
				field:  "Info",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetBannerInfoReplyMultiError(errors)
	}

	return nil
}

// GetBannerInfoReplyMultiError is an error wrapping multiple validation errors
// returned by GetBannerInfoReply.ValidateAll() if the designated constraints
// aren't met.
type GetBannerInfoReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetBannerInfoReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetBannerInfoReplyMultiError) AllErrors() []error { return m }

// GetBannerInfoReplyValidationError is the validation error returned by
// GetBannerInfoReply.Validate if the designated constraints aren't met.
type GetBannerInfoReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetBannerInfoReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetBannerInfoReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetBannerInfoReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetBannerInfoReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetBannerInfoReplyValidationError) ErrorName() string {
	return "GetBannerInfoReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetBannerInfoReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetBannerInfoReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetBannerInfoReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetBannerInfoReplyValidationError{}

// Validate checks the field values on GetBannerListReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetBannerListReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetBannerListReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetBannerListReqMultiError, or nil if none found.
func (m *GetBannerListReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetBannerListReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Page

	// no validation rules for PageSize

	// no validation rules for Title

	// no validation rules for Position

	// no validation rules for Platform

	// no validation rules for LinkType

	// no validation rules for Status

	if len(errors) > 0 {
		return GetBannerListReqMultiError(errors)
	}

	return nil
}

// GetBannerListReqMultiError is an error wrapping multiple validation errors
// returned by GetBannerListReq.ValidateAll() if the designated constraints
// aren't met.
type GetBannerListReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetBannerListReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetBannerListReqMultiError) AllErrors() []error { return m }

// GetBannerListReqValidationError is the validation error returned by
// GetBannerListReq.Validate if the designated constraints aren't met.
type GetBannerListReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetBannerListReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetBannerListReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetBannerListReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetBannerListReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetBannerListReqValidationError) ErrorName() string { return "GetBannerListReqValidationError" }

// Error satisfies the builtin error interface
func (e GetBannerListReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetBannerListReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetBannerListReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetBannerListReqValidationError{}

// Validate checks the field values on GetBannerListReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetBannerListReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetBannerListReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetBannerListReplyMultiError, or nil if none found.
func (m *GetBannerListReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetBannerListReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Total

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetBannerListReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetBannerListReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetBannerListReplyValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetBannerListReplyMultiError(errors)
	}

	return nil
}

// GetBannerListReplyMultiError is an error wrapping multiple validation errors
// returned by GetBannerListReply.ValidateAll() if the designated constraints
// aren't met.
type GetBannerListReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetBannerListReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetBannerListReplyMultiError) AllErrors() []error { return m }

// GetBannerListReplyValidationError is the validation error returned by
// GetBannerListReply.Validate if the designated constraints aren't met.
type GetBannerListReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetBannerListReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetBannerListReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetBannerListReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetBannerListReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetBannerListReplyValidationError) ErrorName() string {
	return "GetBannerListReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetBannerListReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetBannerListReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetBannerListReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetBannerListReplyValidationError{}
