// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.5.3
// - protoc             v3.21.9
// source: admin/v1/banner.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationBannerCreateBanner = "/admin.v1.Banner/CreateBanner"
const OperationBannerDeleteBanner = "/admin.v1.Banner/DeleteBanner"
const OperationBannerGetBannerInfo = "/admin.v1.Banner/GetBannerInfo"
const OperationBannerGetBannerList = "/admin.v1.Banner/GetBannerList"
const OperationBannerUpdateBanner = "/admin.v1.Banner/UpdateBanner"
const OperationBannerUpdateBannerStatus = "/admin.v1.Banner/UpdateBannerStatus"

type BannerHTTPServer interface {
	CreateBanner(context.Context, *CreateBannerReq) (*CreateBannerReply, error)
	DeleteBanner(context.Context, *DeleteBannerReq) (*DeleteBannerReply, error)
	GetBannerInfo(context.Context, *GetBannerInfoReq) (*GetBannerInfoReply, error)
	GetBannerList(context.Context, *GetBannerListReq) (*GetBannerListReply, error)
	UpdateBanner(context.Context, *UpdateBannerReq) (*UpdateBannerReply, error)
	UpdateBannerStatus(context.Context, *UpdateBannerStatusReq) (*UpdateBannerStatusReply, error)
}

func RegisterBannerHTTPServer(s *http.Server, srv BannerHTTPServer) {
	r := s.Route("/")
	r.POST("/admin/v1/banner/create", _Banner_CreateBanner0_HTTP_Handler(srv))
	r.POST("/admin/v1/banner/update", _Banner_UpdateBanner0_HTTP_Handler(srv))
	r.POST("/admin/v1/banner/update/status", _Banner_UpdateBannerStatus0_HTTP_Handler(srv))
	r.POST("/admin/v1/banner/delete", _Banner_DeleteBanner0_HTTP_Handler(srv))
	r.GET("/admin/v1/banner/info", _Banner_GetBannerInfo0_HTTP_Handler(srv))
	r.GET("/admin/v1/banner/list", _Banner_GetBannerList0_HTTP_Handler(srv))
}

func _Banner_CreateBanner0_HTTP_Handler(srv BannerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateBannerReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBannerCreateBanner)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateBanner(ctx, req.(*CreateBannerReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateBannerReply)
		return ctx.Result(200, reply)
	}
}

func _Banner_UpdateBanner0_HTTP_Handler(srv BannerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateBannerReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBannerUpdateBanner)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateBanner(ctx, req.(*UpdateBannerReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateBannerReply)
		return ctx.Result(200, reply)
	}
}

func _Banner_UpdateBannerStatus0_HTTP_Handler(srv BannerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateBannerStatusReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBannerUpdateBannerStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateBannerStatus(ctx, req.(*UpdateBannerStatusReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateBannerStatusReply)
		return ctx.Result(200, reply)
	}
}

func _Banner_DeleteBanner0_HTTP_Handler(srv BannerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteBannerReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBannerDeleteBanner)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteBanner(ctx, req.(*DeleteBannerReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteBannerReply)
		return ctx.Result(200, reply)
	}
}

func _Banner_GetBannerInfo0_HTTP_Handler(srv BannerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetBannerInfoReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBannerGetBannerInfo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetBannerInfo(ctx, req.(*GetBannerInfoReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetBannerInfoReply)
		return ctx.Result(200, reply)
	}
}

func _Banner_GetBannerList0_HTTP_Handler(srv BannerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetBannerListReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBannerGetBannerList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetBannerList(ctx, req.(*GetBannerListReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetBannerListReply)
		return ctx.Result(200, reply)
	}
}

type BannerHTTPClient interface {
	CreateBanner(ctx context.Context, req *CreateBannerReq, opts ...http.CallOption) (rsp *CreateBannerReply, err error)
	DeleteBanner(ctx context.Context, req *DeleteBannerReq, opts ...http.CallOption) (rsp *DeleteBannerReply, err error)
	GetBannerInfo(ctx context.Context, req *GetBannerInfoReq, opts ...http.CallOption) (rsp *GetBannerInfoReply, err error)
	GetBannerList(ctx context.Context, req *GetBannerListReq, opts ...http.CallOption) (rsp *GetBannerListReply, err error)
	UpdateBanner(ctx context.Context, req *UpdateBannerReq, opts ...http.CallOption) (rsp *UpdateBannerReply, err error)
	UpdateBannerStatus(ctx context.Context, req *UpdateBannerStatusReq, opts ...http.CallOption) (rsp *UpdateBannerStatusReply, err error)
}

type BannerHTTPClientImpl struct {
	cc *http.Client
}

func NewBannerHTTPClient(client *http.Client) BannerHTTPClient {
	return &BannerHTTPClientImpl{client}
}

func (c *BannerHTTPClientImpl) CreateBanner(ctx context.Context, in *CreateBannerReq, opts ...http.CallOption) (*CreateBannerReply, error) {
	var out CreateBannerReply
	pattern := "/admin/v1/banner/create"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBannerCreateBanner))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BannerHTTPClientImpl) DeleteBanner(ctx context.Context, in *DeleteBannerReq, opts ...http.CallOption) (*DeleteBannerReply, error) {
	var out DeleteBannerReply
	pattern := "/admin/v1/banner/delete"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBannerDeleteBanner))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BannerHTTPClientImpl) GetBannerInfo(ctx context.Context, in *GetBannerInfoReq, opts ...http.CallOption) (*GetBannerInfoReply, error) {
	var out GetBannerInfoReply
	pattern := "/admin/v1/banner/info"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBannerGetBannerInfo))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BannerHTTPClientImpl) GetBannerList(ctx context.Context, in *GetBannerListReq, opts ...http.CallOption) (*GetBannerListReply, error) {
	var out GetBannerListReply
	pattern := "/admin/v1/banner/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBannerGetBannerList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BannerHTTPClientImpl) UpdateBanner(ctx context.Context, in *UpdateBannerReq, opts ...http.CallOption) (*UpdateBannerReply, error) {
	var out UpdateBannerReply
	pattern := "/admin/v1/banner/update"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBannerUpdateBanner))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BannerHTTPClientImpl) UpdateBannerStatus(ctx context.Context, in *UpdateBannerStatusReq, opts ...http.CallOption) (*UpdateBannerStatusReply, error) {
	var out UpdateBannerStatusReply
	pattern := "/admin/v1/banner/update/status"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBannerUpdateBannerStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
