// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: admin/v1/membership_benefit_type.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MembershipBenefitTypeClient is the client API for MembershipBenefitType service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MembershipBenefitTypeClient interface {
	// 会员权益类型表-创建一条数据
	CreateMembershipBenefitType(ctx context.Context, in *CreateMembershipBenefitTypeReq, opts ...grpc.CallOption) (*CreateMembershipBenefitTypeReply, error)
	// 会员权益类型表-更新一条数据
	UpdateMembershipBenefitType(ctx context.Context, in *UpdateMembershipBenefitTypeReq, opts ...grpc.CallOption) (*UpdateMembershipBenefitTypeReply, error)
	// 会员权益类型表-更新状态
	UpdateMembershipBenefitTypeStatus(ctx context.Context, in *UpdateMembershipBenefitTypeStatusReq, opts ...grpc.CallOption) (*UpdateMembershipBenefitTypeStatusReply, error)
	// 会员权益类型表-删除一条数据
	DeleteMembershipBenefitType(ctx context.Context, in *DeleteMembershipBenefitTypeReq, opts ...grpc.CallOption) (*DeleteMembershipBenefitTypeReply, error)
	// 会员权益类型表-单条数据查询
	GetMembershipBenefitTypeInfo(ctx context.Context, in *GetMembershipBenefitTypeInfoReq, opts ...grpc.CallOption) (*GetMembershipBenefitTypeInfoReply, error)
	// 会员权益类型表-列表数据查询
	GetMembershipBenefitTypeList(ctx context.Context, in *GetMembershipBenefitTypeListReq, opts ...grpc.CallOption) (*GetMembershipBenefitTypeListReply, error)
}

type membershipBenefitTypeClient struct {
	cc grpc.ClientConnInterface
}

func NewMembershipBenefitTypeClient(cc grpc.ClientConnInterface) MembershipBenefitTypeClient {
	return &membershipBenefitTypeClient{cc}
}

func (c *membershipBenefitTypeClient) CreateMembershipBenefitType(ctx context.Context, in *CreateMembershipBenefitTypeReq, opts ...grpc.CallOption) (*CreateMembershipBenefitTypeReply, error) {
	out := new(CreateMembershipBenefitTypeReply)
	err := c.cc.Invoke(ctx, "/admin.v1.MembershipBenefitType/CreateMembershipBenefitType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipBenefitTypeClient) UpdateMembershipBenefitType(ctx context.Context, in *UpdateMembershipBenefitTypeReq, opts ...grpc.CallOption) (*UpdateMembershipBenefitTypeReply, error) {
	out := new(UpdateMembershipBenefitTypeReply)
	err := c.cc.Invoke(ctx, "/admin.v1.MembershipBenefitType/UpdateMembershipBenefitType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipBenefitTypeClient) UpdateMembershipBenefitTypeStatus(ctx context.Context, in *UpdateMembershipBenefitTypeStatusReq, opts ...grpc.CallOption) (*UpdateMembershipBenefitTypeStatusReply, error) {
	out := new(UpdateMembershipBenefitTypeStatusReply)
	err := c.cc.Invoke(ctx, "/admin.v1.MembershipBenefitType/UpdateMembershipBenefitTypeStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipBenefitTypeClient) DeleteMembershipBenefitType(ctx context.Context, in *DeleteMembershipBenefitTypeReq, opts ...grpc.CallOption) (*DeleteMembershipBenefitTypeReply, error) {
	out := new(DeleteMembershipBenefitTypeReply)
	err := c.cc.Invoke(ctx, "/admin.v1.MembershipBenefitType/DeleteMembershipBenefitType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipBenefitTypeClient) GetMembershipBenefitTypeInfo(ctx context.Context, in *GetMembershipBenefitTypeInfoReq, opts ...grpc.CallOption) (*GetMembershipBenefitTypeInfoReply, error) {
	out := new(GetMembershipBenefitTypeInfoReply)
	err := c.cc.Invoke(ctx, "/admin.v1.MembershipBenefitType/GetMembershipBenefitTypeInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipBenefitTypeClient) GetMembershipBenefitTypeList(ctx context.Context, in *GetMembershipBenefitTypeListReq, opts ...grpc.CallOption) (*GetMembershipBenefitTypeListReply, error) {
	out := new(GetMembershipBenefitTypeListReply)
	err := c.cc.Invoke(ctx, "/admin.v1.MembershipBenefitType/GetMembershipBenefitTypeList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MembershipBenefitTypeServer is the server API for MembershipBenefitType service.
// All implementations must embed UnimplementedMembershipBenefitTypeServer
// for forward compatibility
type MembershipBenefitTypeServer interface {
	// 会员权益类型表-创建一条数据
	CreateMembershipBenefitType(context.Context, *CreateMembershipBenefitTypeReq) (*CreateMembershipBenefitTypeReply, error)
	// 会员权益类型表-更新一条数据
	UpdateMembershipBenefitType(context.Context, *UpdateMembershipBenefitTypeReq) (*UpdateMembershipBenefitTypeReply, error)
	// 会员权益类型表-更新状态
	UpdateMembershipBenefitTypeStatus(context.Context, *UpdateMembershipBenefitTypeStatusReq) (*UpdateMembershipBenefitTypeStatusReply, error)
	// 会员权益类型表-删除一条数据
	DeleteMembershipBenefitType(context.Context, *DeleteMembershipBenefitTypeReq) (*DeleteMembershipBenefitTypeReply, error)
	// 会员权益类型表-单条数据查询
	GetMembershipBenefitTypeInfo(context.Context, *GetMembershipBenefitTypeInfoReq) (*GetMembershipBenefitTypeInfoReply, error)
	// 会员权益类型表-列表数据查询
	GetMembershipBenefitTypeList(context.Context, *GetMembershipBenefitTypeListReq) (*GetMembershipBenefitTypeListReply, error)
	mustEmbedUnimplementedMembershipBenefitTypeServer()
}

// UnimplementedMembershipBenefitTypeServer must be embedded to have forward compatible implementations.
type UnimplementedMembershipBenefitTypeServer struct {
}

func (UnimplementedMembershipBenefitTypeServer) CreateMembershipBenefitType(context.Context, *CreateMembershipBenefitTypeReq) (*CreateMembershipBenefitTypeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMembershipBenefitType not implemented")
}
func (UnimplementedMembershipBenefitTypeServer) UpdateMembershipBenefitType(context.Context, *UpdateMembershipBenefitTypeReq) (*UpdateMembershipBenefitTypeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMembershipBenefitType not implemented")
}
func (UnimplementedMembershipBenefitTypeServer) UpdateMembershipBenefitTypeStatus(context.Context, *UpdateMembershipBenefitTypeStatusReq) (*UpdateMembershipBenefitTypeStatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMembershipBenefitTypeStatus not implemented")
}
func (UnimplementedMembershipBenefitTypeServer) DeleteMembershipBenefitType(context.Context, *DeleteMembershipBenefitTypeReq) (*DeleteMembershipBenefitTypeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMembershipBenefitType not implemented")
}
func (UnimplementedMembershipBenefitTypeServer) GetMembershipBenefitTypeInfo(context.Context, *GetMembershipBenefitTypeInfoReq) (*GetMembershipBenefitTypeInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMembershipBenefitTypeInfo not implemented")
}
func (UnimplementedMembershipBenefitTypeServer) GetMembershipBenefitTypeList(context.Context, *GetMembershipBenefitTypeListReq) (*GetMembershipBenefitTypeListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMembershipBenefitTypeList not implemented")
}
func (UnimplementedMembershipBenefitTypeServer) mustEmbedUnimplementedMembershipBenefitTypeServer() {}

// UnsafeMembershipBenefitTypeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MembershipBenefitTypeServer will
// result in compilation errors.
type UnsafeMembershipBenefitTypeServer interface {
	mustEmbedUnimplementedMembershipBenefitTypeServer()
}

func RegisterMembershipBenefitTypeServer(s grpc.ServiceRegistrar, srv MembershipBenefitTypeServer) {
	s.RegisterService(&MembershipBenefitType_ServiceDesc, srv)
}

func _MembershipBenefitType_CreateMembershipBenefitType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMembershipBenefitTypeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipBenefitTypeServer).CreateMembershipBenefitType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.v1.MembershipBenefitType/CreateMembershipBenefitType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipBenefitTypeServer).CreateMembershipBenefitType(ctx, req.(*CreateMembershipBenefitTypeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipBenefitType_UpdateMembershipBenefitType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMembershipBenefitTypeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipBenefitTypeServer).UpdateMembershipBenefitType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.v1.MembershipBenefitType/UpdateMembershipBenefitType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipBenefitTypeServer).UpdateMembershipBenefitType(ctx, req.(*UpdateMembershipBenefitTypeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipBenefitType_UpdateMembershipBenefitTypeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMembershipBenefitTypeStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipBenefitTypeServer).UpdateMembershipBenefitTypeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.v1.MembershipBenefitType/UpdateMembershipBenefitTypeStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipBenefitTypeServer).UpdateMembershipBenefitTypeStatus(ctx, req.(*UpdateMembershipBenefitTypeStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipBenefitType_DeleteMembershipBenefitType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMembershipBenefitTypeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipBenefitTypeServer).DeleteMembershipBenefitType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.v1.MembershipBenefitType/DeleteMembershipBenefitType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipBenefitTypeServer).DeleteMembershipBenefitType(ctx, req.(*DeleteMembershipBenefitTypeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipBenefitType_GetMembershipBenefitTypeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMembershipBenefitTypeInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipBenefitTypeServer).GetMembershipBenefitTypeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.v1.MembershipBenefitType/GetMembershipBenefitTypeInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipBenefitTypeServer).GetMembershipBenefitTypeInfo(ctx, req.(*GetMembershipBenefitTypeInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipBenefitType_GetMembershipBenefitTypeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMembershipBenefitTypeListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipBenefitTypeServer).GetMembershipBenefitTypeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.v1.MembershipBenefitType/GetMembershipBenefitTypeList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipBenefitTypeServer).GetMembershipBenefitTypeList(ctx, req.(*GetMembershipBenefitTypeListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// MembershipBenefitType_ServiceDesc is the grpc.ServiceDesc for MembershipBenefitType service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MembershipBenefitType_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.v1.MembershipBenefitType",
	HandlerType: (*MembershipBenefitTypeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMembershipBenefitType",
			Handler:    _MembershipBenefitType_CreateMembershipBenefitType_Handler,
		},
		{
			MethodName: "UpdateMembershipBenefitType",
			Handler:    _MembershipBenefitType_UpdateMembershipBenefitType_Handler,
		},
		{
			MethodName: "UpdateMembershipBenefitTypeStatus",
			Handler:    _MembershipBenefitType_UpdateMembershipBenefitTypeStatus_Handler,
		},
		{
			MethodName: "DeleteMembershipBenefitType",
			Handler:    _MembershipBenefitType_DeleteMembershipBenefitType_Handler,
		},
		{
			MethodName: "GetMembershipBenefitTypeInfo",
			Handler:    _MembershipBenefitType_GetMembershipBenefitTypeInfo_Handler,
		},
		{
			MethodName: "GetMembershipBenefitTypeList",
			Handler:    _MembershipBenefitType_GetMembershipBenefitTypeList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin/v1/membership_benefit_type.proto",
}
