// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: admin/v1/user_message.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UserMessageInfo with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UserMessageInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserMessageInfo with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UserMessageInfoMultiError, or nil if none found.
func (m *UserMessageInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *UserMessageInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for MessageId

	// no validation rules for UserId

	// no validation rules for Category

	// no validation rules for Title

	// no validation rules for Summary

	// no validation rules for CoverURL

	// no validation rules for Content

	// no validation rules for LinkURL

	// no validation rules for AudienceType

	// no validation rules for AudienceValue

	// no validation rules for SentAt

	// no validation rules for ReadAt

	// no validation rules for AdminId

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return UserMessageInfoMultiError(errors)
	}

	return nil
}

// UserMessageInfoMultiError is an error wrapping multiple validation errors
// returned by UserMessageInfo.ValidateAll() if the designated constraints
// aren't met.
type UserMessageInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserMessageInfoMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserMessageInfoMultiError) AllErrors() []error { return m }

// UserMessageInfoValidationError is the validation error returned by
// UserMessageInfo.Validate if the designated constraints aren't met.
type UserMessageInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserMessageInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserMessageInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserMessageInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserMessageInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserMessageInfoValidationError) ErrorName() string { return "UserMessageInfoValidationError" }

// Error satisfies the builtin error interface
func (e UserMessageInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserMessageInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserMessageInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserMessageInfoValidationError{}

// Validate checks the field values on SendUserMessageReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SendUserMessageReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendUserMessageReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SendUserMessageReqMultiError, or nil if none found.
func (m *SendUserMessageReq) ValidateAll() error {
	return m.validate(true)
}

func (m *SendUserMessageReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Category

	// no validation rules for Title

	// no validation rules for Summary

	// no validation rules for CoverURL

	// no validation rules for Content

	// no validation rules for LinkURL

	// no validation rules for AudienceType

	// no validation rules for MembershipType

	// no validation rules for ActiveWithinDays

	if len(errors) > 0 {
		return SendUserMessageReqMultiError(errors)
	}

	return nil
}

// SendUserMessageReqMultiError is an error wrapping multiple validation errors
// returned by SendUserMessageReq.ValidateAll() if the designated constraints
// aren't met.
type SendUserMessageReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendUserMessageReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendUserMessageReqMultiError) AllErrors() []error { return m }

// SendUserMessageReqValidationError is the validation error returned by
// SendUserMessageReq.Validate if the designated constraints aren't met.
type SendUserMessageReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendUserMessageReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendUserMessageReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendUserMessageReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendUserMessageReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendUserMessageReqValidationError) ErrorName() string {
	return "SendUserMessageReqValidationError"
}

// Error satisfies the builtin error interface
func (e SendUserMessageReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendUserMessageReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendUserMessageReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendUserMessageReqValidationError{}

// Validate checks the field values on SendUserMessageReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SendUserMessageReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendUserMessageReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SendUserMessageReplyMultiError, or nil if none found.
func (m *SendUserMessageReply) ValidateAll() error {
	return m.validate(true)
}

func (m *SendUserMessageReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for MessageId

	// no validation rules for Total

	if len(errors) > 0 {
		return SendUserMessageReplyMultiError(errors)
	}

	return nil
}

// SendUserMessageReplyMultiError is an error wrapping multiple validation
// errors returned by SendUserMessageReply.ValidateAll() if the designated
// constraints aren't met.
type SendUserMessageReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendUserMessageReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendUserMessageReplyMultiError) AllErrors() []error { return m }

// SendUserMessageReplyValidationError is the validation error returned by
// SendUserMessageReply.Validate if the designated constraints aren't met.
type SendUserMessageReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendUserMessageReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendUserMessageReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendUserMessageReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendUserMessageReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendUserMessageReplyValidationError) ErrorName() string {
	return "SendUserMessageReplyValidationError"
}

// Error satisfies the builtin error interface
func (e SendUserMessageReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendUserMessageReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendUserMessageReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendUserMessageReplyValidationError{}

// Validate checks the field values on GetUserMessageInfoReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUserMessageInfoReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserMessageInfoReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserMessageInfoReqMultiError, or nil if none found.
func (m *GetUserMessageInfoReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserMessageInfoReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return GetUserMessageInfoReqMultiError(errors)
	}

	return nil
}

// GetUserMessageInfoReqMultiError is an error wrapping multiple validation
// errors returned by GetUserMessageInfoReq.ValidateAll() if the designated
// constraints aren't met.
type GetUserMessageInfoReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserMessageInfoReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserMessageInfoReqMultiError) AllErrors() []error { return m }

// GetUserMessageInfoReqValidationError is the validation error returned by
// GetUserMessageInfoReq.Validate if the designated constraints aren't met.
type GetUserMessageInfoReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserMessageInfoReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserMessageInfoReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserMessageInfoReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserMessageInfoReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserMessageInfoReqValidationError) ErrorName() string {
	return "GetUserMessageInfoReqValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserMessageInfoReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserMessageInfoReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserMessageInfoReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserMessageInfoReqValidationError{}

// Validate checks the field values on GetUserMessageInfoReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUserMessageInfoReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserMessageInfoReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserMessageInfoReplyMultiError, or nil if none found.
func (m *GetUserMessageInfoReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserMessageInfoReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetUserMessageInfoReplyValidationError{
					field:  "Info",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetUserMessageInfoReplyValidationError{
					field:  "Info",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetUserMessageInfoReplyValidationError{
				field:  "Info",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetUserMessageInfoReplyMultiError(errors)
	}

	return nil
}

// GetUserMessageInfoReplyMultiError is an error wrapping multiple validation
// errors returned by GetUserMessageInfoReply.ValidateAll() if the designated
// constraints aren't met.
type GetUserMessageInfoReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserMessageInfoReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserMessageInfoReplyMultiError) AllErrors() []error { return m }

// GetUserMessageInfoReplyValidationError is the validation error returned by
// GetUserMessageInfoReply.Validate if the designated constraints aren't met.
type GetUserMessageInfoReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserMessageInfoReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserMessageInfoReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserMessageInfoReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserMessageInfoReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserMessageInfoReplyValidationError) ErrorName() string {
	return "GetUserMessageInfoReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserMessageInfoReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserMessageInfoReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserMessageInfoReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserMessageInfoReplyValidationError{}

// Validate checks the field values on GetUserMessageListReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUserMessageListReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserMessageListReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserMessageListReqMultiError, or nil if none found.
func (m *GetUserMessageListReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserMessageListReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Page

	// no validation rules for PageSize

	// no validation rules for Category

	// no validation rules for Title

	// no validation rules for UserId

	// no validation rules for MessageId

	// no validation rules for AudienceType

	// no validation rules for ReadStatus

	if len(errors) > 0 {
		return GetUserMessageListReqMultiError(errors)
	}

	return nil
}

// GetUserMessageListReqMultiError is an error wrapping multiple validation
// errors returned by GetUserMessageListReq.ValidateAll() if the designated
// constraints aren't met.
type GetUserMessageListReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserMessageListReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserMessageListReqMultiError) AllErrors() []error { return m }

// GetUserMessageListReqValidationError is the validation error returned by
// GetUserMessageListReq.Validate if the designated constraints aren't met.
type GetUserMessageListReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserMessageListReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserMessageListReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserMessageListReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserMessageListReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserMessageListReqValidationError) ErrorName() string {
	return "GetUserMessageListReqValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserMessageListReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserMessageListReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserMessageListReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserMessageListReqValidationError{}

// Validate checks the field values on GetUserMessageListReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUserMessageListReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserMessageListReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserMessageListReplyMultiError, or nil if none found.
func (m *GetUserMessageListReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserMessageListReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Total

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetUserMessageListReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetUserMessageListReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetUserMessageListReplyValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetUserMessageListReplyMultiError(errors)
	}

	return nil
}

// GetUserMessageListReplyMultiError is an error wrapping multiple validation
// errors returned by GetUserMessageListReply.ValidateAll() if the designated
// constraints aren't met.
type GetUserMessageListReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserMessageListReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserMessageListReplyMultiError) AllErrors() []error { return m }

// GetUserMessageListReplyValidationError is the validation error returned by
// GetUserMessageListReply.Validate if the designated constraints aren't met.
type GetUserMessageListReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserMessageListReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserMessageListReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserMessageListReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserMessageListReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserMessageListReplyValidationError) ErrorName() string {
	return "GetUserMessageListReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserMessageListReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserMessageListReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserMessageListReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserMessageListReplyValidationError{}
