// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: admin/v1/user_membership_change.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UserMembershipChangeItem with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UserMembershipChangeItem) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserMembershipChangeItem with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UserMembershipChangeItemMultiError, or nil if none found.
func (m *UserMembershipChangeItem) ValidateAll() error {
	return m.validate(true)
}

func (m *UserMembershipChangeItem) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for MembershipType

	// no validation rules for ExpiredAt

	// no validation rules for AutoRenew

	// no validation rules for AutoRenewDays

	// no validation rules for Status

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return UserMembershipChangeItemMultiError(errors)
	}

	return nil
}

// UserMembershipChangeItemMultiError is an error wrapping multiple validation
// errors returned by UserMembershipChangeItem.ValidateAll() if the designated
// constraints aren't met.
type UserMembershipChangeItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserMembershipChangeItemMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserMembershipChangeItemMultiError) AllErrors() []error { return m }

// UserMembershipChangeItemValidationError is the validation error returned by
// UserMembershipChangeItem.Validate if the designated constraints aren't met.
type UserMembershipChangeItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserMembershipChangeItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserMembershipChangeItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserMembershipChangeItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserMembershipChangeItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserMembershipChangeItemValidationError) ErrorName() string {
	return "UserMembershipChangeItemValidationError"
}

// Error satisfies the builtin error interface
func (e UserMembershipChangeItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserMembershipChangeItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserMembershipChangeItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserMembershipChangeItemValidationError{}

// Validate checks the field values on UserMembershipChangeInfo with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UserMembershipChangeInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserMembershipChangeInfo with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UserMembershipChangeInfoMultiError, or nil if none found.
func (m *UserMembershipChangeInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *UserMembershipChangeInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for UserId

	// no validation rules for SourceType

	// no validation rules for SourceId

	if all {
		switch v := interface{}(m.GetBefore()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UserMembershipChangeInfoValidationError{
					field:  "Before",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UserMembershipChangeInfoValidationError{
					field:  "Before",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetBefore()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UserMembershipChangeInfoValidationError{
				field:  "Before",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetAfter()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UserMembershipChangeInfoValidationError{
					field:  "After",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UserMembershipChangeInfoValidationError{
					field:  "After",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAfter()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UserMembershipChangeInfoValidationError{
				field:  "After",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Remark

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return UserMembershipChangeInfoMultiError(errors)
	}

	return nil
}

// UserMembershipChangeInfoMultiError is an error wrapping multiple validation
// errors returned by UserMembershipChangeInfo.ValidateAll() if the designated
// constraints aren't met.
type UserMembershipChangeInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserMembershipChangeInfoMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserMembershipChangeInfoMultiError) AllErrors() []error { return m }

// UserMembershipChangeInfoValidationError is the validation error returned by
// UserMembershipChangeInfo.Validate if the designated constraints aren't met.
type UserMembershipChangeInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserMembershipChangeInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserMembershipChangeInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserMembershipChangeInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserMembershipChangeInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserMembershipChangeInfoValidationError) ErrorName() string {
	return "UserMembershipChangeInfoValidationError"
}

// Error satisfies the builtin error interface
func (e UserMembershipChangeInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserMembershipChangeInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserMembershipChangeInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserMembershipChangeInfoValidationError{}

// Validate checks the field values on GetUserMembershipChangeListReq with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUserMembershipChangeListReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserMembershipChangeListReq with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// GetUserMembershipChangeListReqMultiError, or nil if none found.
func (m *GetUserMembershipChangeListReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserMembershipChangeListReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Page

	// no validation rules for PageSize

	// no validation rules for UserId

	// no validation rules for SourceType

	// no validation rules for SourceId

	if len(errors) > 0 {
		return GetUserMembershipChangeListReqMultiError(errors)
	}

	return nil
}

// GetUserMembershipChangeListReqMultiError is an error wrapping multiple
// validation errors returned by GetUserMembershipChangeListReq.ValidateAll()
// if the designated constraints aren't met.
type GetUserMembershipChangeListReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserMembershipChangeListReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserMembershipChangeListReqMultiError) AllErrors() []error { return m }

// GetUserMembershipChangeListReqValidationError is the validation error
// returned by GetUserMembershipChangeListReq.Validate if the designated
// constraints aren't met.
type GetUserMembershipChangeListReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserMembershipChangeListReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserMembershipChangeListReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserMembershipChangeListReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserMembershipChangeListReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserMembershipChangeListReqValidationError) ErrorName() string {
	return "GetUserMembershipChangeListReqValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserMembershipChangeListReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserMembershipChangeListReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserMembershipChangeListReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserMembershipChangeListReqValidationError{}

// Validate checks the field values on GetUserMembershipChangeListReply with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *GetUserMembershipChangeListReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserMembershipChangeListReply with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// GetUserMembershipChangeListReplyMultiError, or nil if none found.
func (m *GetUserMembershipChangeListReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserMembershipChangeListReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Total

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetUserMembershipChangeListReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetUserMembershipChangeListReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetUserMembershipChangeListReplyValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetUserMembershipChangeListReplyMultiError(errors)
	}

	return nil
}

// GetUserMembershipChangeListReplyMultiError is an error wrapping multiple
// validation errors returned by
// GetUserMembershipChangeListReply.ValidateAll() if the designated
// constraints aren't met.
type GetUserMembershipChangeListReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserMembershipChangeListReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserMembershipChangeListReplyMultiError) AllErrors() []error { return m }

// GetUserMembershipChangeListReplyValidationError is the validation error
// returned by GetUserMembershipChangeListReply.Validate if the designated
// constraints aren't met.
type GetUserMembershipChangeListReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserMembershipChangeListReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserMembershipChangeListReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserMembershipChangeListReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserMembershipChangeListReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserMembershipChangeListReplyValidationError) ErrorName() string {
	return "GetUserMembershipChangeListReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserMembershipChangeListReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserMembershipChangeListReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserMembershipChangeListReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserMembershipChangeListReplyValidationError{}
