// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: admin/v1/user_membership_change.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserMembershipChangeRecordClient is the client API for UserMembershipChangeRecord service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserMembershipChangeRecordClient interface {
	// 用户会员变更记录表-列表数据查询
	GetUserMembershipChangeList(ctx context.Context, in *GetUserMembershipChangeListReq, opts ...grpc.CallOption) (*GetUserMembershipChangeListReply, error)
}

type userMembershipChangeRecordClient struct {
	cc grpc.ClientConnInterface
}

func NewUserMembershipChangeRecordClient(cc grpc.ClientConnInterface) UserMembershipChangeRecordClient {
	return &userMembershipChangeRecordClient{cc}
}

func (c *userMembershipChangeRecordClient) GetUserMembershipChangeList(ctx context.Context, in *GetUserMembershipChangeListReq, opts ...grpc.CallOption) (*GetUserMembershipChangeListReply, error) {
	out := new(GetUserMembershipChangeListReply)
	err := c.cc.Invoke(ctx, "/admin.v1.UserMembershipChangeRecord/GetUserMembershipChangeList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserMembershipChangeRecordServer is the server API for UserMembershipChangeRecord service.
// All implementations must embed UnimplementedUserMembershipChangeRecordServer
// for forward compatibility
type UserMembershipChangeRecordServer interface {
	// 用户会员变更记录表-列表数据查询
	GetUserMembershipChangeList(context.Context, *GetUserMembershipChangeListReq) (*GetUserMembershipChangeListReply, error)
	mustEmbedUnimplementedUserMembershipChangeRecordServer()
}

// UnimplementedUserMembershipChangeRecordServer must be embedded to have forward compatible implementations.
type UnimplementedUserMembershipChangeRecordServer struct {
}

func (UnimplementedUserMembershipChangeRecordServer) GetUserMembershipChangeList(context.Context, *GetUserMembershipChangeListReq) (*GetUserMembershipChangeListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserMembershipChangeList not implemented")
}
func (UnimplementedUserMembershipChangeRecordServer) mustEmbedUnimplementedUserMembershipChangeRecordServer() {
}

// UnsafeUserMembershipChangeRecordServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserMembershipChangeRecordServer will
// result in compilation errors.
type UnsafeUserMembershipChangeRecordServer interface {
	mustEmbedUnimplementedUserMembershipChangeRecordServer()
}

func RegisterUserMembershipChangeRecordServer(s grpc.ServiceRegistrar, srv UserMembershipChangeRecordServer) {
	s.RegisterService(&UserMembershipChangeRecord_ServiceDesc, srv)
}

func _UserMembershipChangeRecord_GetUserMembershipChangeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserMembershipChangeListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserMembershipChangeRecordServer).GetUserMembershipChangeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.v1.UserMembershipChangeRecord/GetUserMembershipChangeList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserMembershipChangeRecordServer).GetUserMembershipChangeList(ctx, req.(*GetUserMembershipChangeListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// UserMembershipChangeRecord_ServiceDesc is the grpc.ServiceDesc for UserMembershipChangeRecord service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserMembershipChangeRecord_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.v1.UserMembershipChangeRecord",
	HandlerType: (*UserMembershipChangeRecordServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserMembershipChangeList",
			Handler:    _UserMembershipChangeRecord_GetUserMembershipChangeList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin/v1/user_membership_change.proto",
}
