// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package ai_boilerplate_dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/fzf-labs/ai-boilerplate-backend/internal/data/gorm/ai_boilerplate_model"
)

func newMembershipBenefitType(db *gorm.DB, opts ...gen.DOOption) membershipBenefitType {
	_membershipBenefitType := membershipBenefitType{}

	_membershipBenefitType.membershipBenefitTypeDo.UseDB(db, opts...)
	_membershipBenefitType.membershipBenefitTypeDo.UseModel(&ai_boilerplate_model.MembershipBenefitType{})

	tableName := _membershipBenefitType.membershipBenefitTypeDo.TableName()
	_membershipBenefitType.ALL = field.NewAsterisk(tableName)
	_membershipBenefitType.ID = field.NewString(tableName, "id")
	_membershipBenefitType.BenefitKey = field.NewString(tableName, "benefit_key")
	_membershipBenefitType.BenefitName = field.NewString(tableName, "benefit_name")
	_membershipBenefitType.BenefitIcon = field.NewString(tableName, "benefit_icon")
	_membershipBenefitType.BenefitDesc = field.NewString(tableName, "benefit_desc")
	_membershipBenefitType.Sort = field.NewInt32(tableName, "sort")
	_membershipBenefitType.Status = field.NewInt32(tableName, "status")
	_membershipBenefitType.CreatedAt = field.NewTime(tableName, "created_at")
	_membershipBenefitType.UpdatedAt = field.NewTime(tableName, "updated_at")
	_membershipBenefitType.DeletedAt = field.NewField(tableName, "deleted_at")

	_membershipBenefitType.fillFieldMap()

	return _membershipBenefitType
}

type membershipBenefitType struct {
	membershipBenefitTypeDo membershipBenefitTypeDo

	ALL         field.Asterisk
	ID          field.String // id
	BenefitKey  field.String // 权益标识
	BenefitName field.String // 权益名称
	BenefitIcon field.String // 权益图标
	BenefitDesc field.String // 权益描述
	Sort        field.Int32  // 排序
	Status      field.Int32  // 状态(-1禁用,1启用)
	CreatedAt   field.Time   // 创建时间
	UpdatedAt   field.Time   // 更新时间
	DeletedAt   field.Field  // 删除时间

	fieldMap map[string]field.Expr
}

func (m membershipBenefitType) Table(newTableName string) *membershipBenefitType {
	m.membershipBenefitTypeDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m membershipBenefitType) As(alias string) *membershipBenefitType {
	m.membershipBenefitTypeDo.DO = *(m.membershipBenefitTypeDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *membershipBenefitType) updateTableName(table string) *membershipBenefitType {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewString(table, "id")
	m.BenefitKey = field.NewString(table, "benefit_key")
	m.BenefitName = field.NewString(table, "benefit_name")
	m.BenefitIcon = field.NewString(table, "benefit_icon")
	m.BenefitDesc = field.NewString(table, "benefit_desc")
	m.Sort = field.NewInt32(table, "sort")
	m.Status = field.NewInt32(table, "status")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")
	m.DeletedAt = field.NewField(table, "deleted_at")

	m.fillFieldMap()

	return m
}

func (m *membershipBenefitType) WithContext(ctx context.Context) *membershipBenefitTypeDo {
	return m.membershipBenefitTypeDo.WithContext(ctx)
}

func (m membershipBenefitType) TableName() string { return m.membershipBenefitTypeDo.TableName() }

func (m membershipBenefitType) Alias() string { return m.membershipBenefitTypeDo.Alias() }

func (m membershipBenefitType) Columns(cols ...field.Expr) gen.Columns {
	return m.membershipBenefitTypeDo.Columns(cols...)
}

func (m *membershipBenefitType) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *membershipBenefitType) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 10)
	m.fieldMap["id"] = m.ID
	m.fieldMap["benefit_key"] = m.BenefitKey
	m.fieldMap["benefit_name"] = m.BenefitName
	m.fieldMap["benefit_icon"] = m.BenefitIcon
	m.fieldMap["benefit_desc"] = m.BenefitDesc
	m.fieldMap["sort"] = m.Sort
	m.fieldMap["status"] = m.Status
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
	m.fieldMap["deleted_at"] = m.DeletedAt
}

func (m membershipBenefitType) clone(db *gorm.DB) membershipBenefitType {
	m.membershipBenefitTypeDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m membershipBenefitType) replaceDB(db *gorm.DB) membershipBenefitType {
	m.membershipBenefitTypeDo.ReplaceDB(db)
	return m
}

type membershipBenefitTypeDo struct{ gen.DO }

func (m membershipBenefitTypeDo) Debug() *membershipBenefitTypeDo {
	return m.withDO(m.DO.Debug())
}

func (m membershipBenefitTypeDo) WithContext(ctx context.Context) *membershipBenefitTypeDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m membershipBenefitTypeDo) ReadDB() *membershipBenefitTypeDo {
	return m.Clauses(dbresolver.Read)
}

func (m membershipBenefitTypeDo) WriteDB() *membershipBenefitTypeDo {
	return m.Clauses(dbresolver.Write)
}

func (m membershipBenefitTypeDo) Session(config *gorm.Session) *membershipBenefitTypeDo {
	return m.withDO(m.DO.Session(config))
}

func (m membershipBenefitTypeDo) Clauses(conds ...clause.Expression) *membershipBenefitTypeDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m membershipBenefitTypeDo) Returning(value interface{}, columns ...string) *membershipBenefitTypeDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m membershipBenefitTypeDo) Not(conds ...gen.Condition) *membershipBenefitTypeDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m membershipBenefitTypeDo) Or(conds ...gen.Condition) *membershipBenefitTypeDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m membershipBenefitTypeDo) Select(conds ...field.Expr) *membershipBenefitTypeDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m membershipBenefitTypeDo) Where(conds ...gen.Condition) *membershipBenefitTypeDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m membershipBenefitTypeDo) Order(conds ...field.Expr) *membershipBenefitTypeDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m membershipBenefitTypeDo) Distinct(cols ...field.Expr) *membershipBenefitTypeDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m membershipBenefitTypeDo) Omit(cols ...field.Expr) *membershipBenefitTypeDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m membershipBenefitTypeDo) Join(table schema.Tabler, on ...field.Expr) *membershipBenefitTypeDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m membershipBenefitTypeDo) LeftJoin(table schema.Tabler, on ...field.Expr) *membershipBenefitTypeDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m membershipBenefitTypeDo) RightJoin(table schema.Tabler, on ...field.Expr) *membershipBenefitTypeDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m membershipBenefitTypeDo) Group(cols ...field.Expr) *membershipBenefitTypeDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m membershipBenefitTypeDo) Having(conds ...gen.Condition) *membershipBenefitTypeDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m membershipBenefitTypeDo) Limit(limit int) *membershipBenefitTypeDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m membershipBenefitTypeDo) Offset(offset int) *membershipBenefitTypeDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m membershipBenefitTypeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *membershipBenefitTypeDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m membershipBenefitTypeDo) Unscoped() *membershipBenefitTypeDo {
	return m.withDO(m.DO.Unscoped())
}

func (m membershipBenefitTypeDo) Create(values ...*ai_boilerplate_model.MembershipBenefitType) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m membershipBenefitTypeDo) CreateInBatches(values []*ai_boilerplate_model.MembershipBenefitType, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m membershipBenefitTypeDo) Save(values ...*ai_boilerplate_model.MembershipBenefitType) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m membershipBenefitTypeDo) First() (*ai_boilerplate_model.MembershipBenefitType, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*ai_boilerplate_model.MembershipBenefitType), nil
	}
}

func (m membershipBenefitTypeDo) Take() (*ai_boilerplate_model.MembershipBenefitType, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*ai_boilerplate_model.MembershipBenefitType), nil
	}
}

func (m membershipBenefitTypeDo) Last() (*ai_boilerplate_model.MembershipBenefitType, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*ai_boilerplate_model.MembershipBenefitType), nil
	}
}

func (m membershipBenefitTypeDo) Find() ([]*ai_boilerplate_model.MembershipBenefitType, error) {
	result, err := m.DO.Find()
	return result.([]*ai_boilerplate_model.MembershipBenefitType), err
}

func (m membershipBenefitTypeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*ai_boilerplate_model.MembershipBenefitType, err error) {
	buf := make([]*ai_boilerplate_model.MembershipBenefitType, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m membershipBenefitTypeDo) FindInBatches(result *[]*ai_boilerplate_model.MembershipBenefitType, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m membershipBenefitTypeDo) Attrs(attrs ...field.AssignExpr) *membershipBenefitTypeDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m membershipBenefitTypeDo) Assign(attrs ...field.AssignExpr) *membershipBenefitTypeDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m membershipBenefitTypeDo) Joins(fields ...field.RelationField) *membershipBenefitTypeDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m membershipBenefitTypeDo) Preload(fields ...field.RelationField) *membershipBenefitTypeDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m membershipBenefitTypeDo) FirstOrInit() (*ai_boilerplate_model.MembershipBenefitType, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*ai_boilerplate_model.MembershipBenefitType), nil
	}
}

func (m membershipBenefitTypeDo) FirstOrCreate() (*ai_boilerplate_model.MembershipBenefitType, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*ai_boilerplate_model.MembershipBenefitType), nil
	}
}

func (m membershipBenefitTypeDo) FindByPage(offset int, limit int) (result []*ai_boilerplate_model.MembershipBenefitType, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m membershipBenefitTypeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m membershipBenefitTypeDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m membershipBenefitTypeDo) Delete(models ...*ai_boilerplate_model.MembershipBenefitType) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *membershipBenefitTypeDo) withDO(do gen.Dao) *membershipBenefitTypeDo {
	m.DO = *do.(*gen.DO)
	return m
}
