// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package ai_boilerplate_dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/fzf-labs/ai-boilerplate-backend/internal/data/gorm/ai_boilerplate_model"
)

func newUserNotificationSetting(db *gorm.DB, opts ...gen.DOOption) userNotificationSetting {
	_userNotificationSetting := userNotificationSetting{}

	_userNotificationSetting.userNotificationSettingDo.UseDB(db, opts...)
	_userNotificationSetting.userNotificationSettingDo.UseModel(&ai_boilerplate_model.UserNotificationSetting{})

	tableName := _userNotificationSetting.userNotificationSettingDo.TableName()
	_userNotificationSetting.ALL = field.NewAsterisk(tableName)
	_userNotificationSetting.ID = field.NewString(tableName, "id")
	_userNotificationSetting.UserID = field.NewString(tableName, "user_id")
	_userNotificationSetting.SystemNotification = field.NewBool(tableName, "system_notification")
	_userNotificationSetting.ActivityNotification = field.NewBool(tableName, "activity_notification")
	_userNotificationSetting.OrderNotification = field.NewBool(tableName, "order_notification")
	_userNotificationSetting.MessageNotification = field.NewBool(tableName, "message_notification")
	_userNotificationSetting.DndEnabled = field.NewBool(tableName, "dnd_enabled")
	_userNotificationSetting.DndStartTime = field.NewString(tableName, "dnd_start_time")
	_userNotificationSetting.DndEndTime = field.NewString(tableName, "dnd_end_time")
	_userNotificationSetting.CreatedAt = field.NewTime(tableName, "created_at")
	_userNotificationSetting.UpdatedAt = field.NewTime(tableName, "updated_at")
	_userNotificationSetting.DeletedAt = field.NewField(tableName, "deleted_at")

	_userNotificationSetting.fillFieldMap()

	return _userNotificationSetting
}

type userNotificationSetting struct {
	userNotificationSettingDo userNotificationSettingDo

	ALL                  field.Asterisk
	ID                   field.String
	UserID               field.String
	SystemNotification   field.Bool
	ActivityNotification field.Bool
	OrderNotification    field.Bool
	MessageNotification  field.Bool
	DndEnabled           field.Bool
	DndStartTime         field.String
	DndEndTime           field.String
	CreatedAt            field.Time
	UpdatedAt            field.Time
	DeletedAt            field.Field

	fieldMap map[string]field.Expr
}

func (u userNotificationSetting) Table(newTableName string) *userNotificationSetting {
	u.userNotificationSettingDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userNotificationSetting) As(alias string) *userNotificationSetting {
	u.userNotificationSettingDo.DO = *(u.userNotificationSettingDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userNotificationSetting) updateTableName(table string) *userNotificationSetting {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewString(table, "id")
	u.UserID = field.NewString(table, "user_id")
	u.SystemNotification = field.NewBool(table, "system_notification")
	u.ActivityNotification = field.NewBool(table, "activity_notification")
	u.OrderNotification = field.NewBool(table, "order_notification")
	u.MessageNotification = field.NewBool(table, "message_notification")
	u.DndEnabled = field.NewBool(table, "dnd_enabled")
	u.DndStartTime = field.NewString(table, "dnd_start_time")
	u.DndEndTime = field.NewString(table, "dnd_end_time")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.UpdatedAt = field.NewTime(table, "updated_at")
	u.DeletedAt = field.NewField(table, "deleted_at")

	u.fillFieldMap()

	return u
}

func (u *userNotificationSetting) WithContext(ctx context.Context) *userNotificationSettingDo {
	return u.userNotificationSettingDo.WithContext(ctx)
}

func (u userNotificationSetting) TableName() string { return u.userNotificationSettingDo.TableName() }

func (u userNotificationSetting) Alias() string { return u.userNotificationSettingDo.Alias() }

func (u userNotificationSetting) Columns(cols ...field.Expr) gen.Columns {
	return u.userNotificationSettingDo.Columns(cols...)
}

func (u *userNotificationSetting) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userNotificationSetting) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 12)
	u.fieldMap["id"] = u.ID
	u.fieldMap["user_id"] = u.UserID
	u.fieldMap["system_notification"] = u.SystemNotification
	u.fieldMap["activity_notification"] = u.ActivityNotification
	u.fieldMap["order_notification"] = u.OrderNotification
	u.fieldMap["message_notification"] = u.MessageNotification
	u.fieldMap["dnd_enabled"] = u.DndEnabled
	u.fieldMap["dnd_start_time"] = u.DndStartTime
	u.fieldMap["dnd_end_time"] = u.DndEndTime
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["updated_at"] = u.UpdatedAt
	u.fieldMap["deleted_at"] = u.DeletedAt
}

func (u userNotificationSetting) clone(db *gorm.DB) userNotificationSetting {
	u.userNotificationSettingDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userNotificationSetting) replaceDB(db *gorm.DB) userNotificationSetting {
	u.userNotificationSettingDo.ReplaceDB(db)
	return u
}

type userNotificationSettingDo struct{ gen.DO }

func (u userNotificationSettingDo) Debug() *userNotificationSettingDo {
	return u.withDO(u.DO.Debug())
}

func (u userNotificationSettingDo) WithContext(ctx context.Context) *userNotificationSettingDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userNotificationSettingDo) ReadDB() *userNotificationSettingDo {
	return u.Clauses(dbresolver.Read)
}

func (u userNotificationSettingDo) WriteDB() *userNotificationSettingDo {
	return u.Clauses(dbresolver.Write)
}

func (u userNotificationSettingDo) Session(config *gorm.Session) *userNotificationSettingDo {
	return u.withDO(u.DO.Session(config))
}

func (u userNotificationSettingDo) Clauses(conds ...clause.Expression) *userNotificationSettingDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userNotificationSettingDo) Returning(value interface{}, columns ...string) *userNotificationSettingDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userNotificationSettingDo) Not(conds ...gen.Condition) *userNotificationSettingDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userNotificationSettingDo) Or(conds ...gen.Condition) *userNotificationSettingDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userNotificationSettingDo) Select(conds ...field.Expr) *userNotificationSettingDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userNotificationSettingDo) Where(conds ...gen.Condition) *userNotificationSettingDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userNotificationSettingDo) Order(conds ...field.Expr) *userNotificationSettingDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userNotificationSettingDo) Distinct(cols ...field.Expr) *userNotificationSettingDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userNotificationSettingDo) Omit(cols ...field.Expr) *userNotificationSettingDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userNotificationSettingDo) Join(table schema.Tabler, on ...field.Expr) *userNotificationSettingDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userNotificationSettingDo) LeftJoin(table schema.Tabler, on ...field.Expr) *userNotificationSettingDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userNotificationSettingDo) RightJoin(table schema.Tabler, on ...field.Expr) *userNotificationSettingDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userNotificationSettingDo) Group(cols ...field.Expr) *userNotificationSettingDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userNotificationSettingDo) Having(conds ...gen.Condition) *userNotificationSettingDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userNotificationSettingDo) Limit(limit int) *userNotificationSettingDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userNotificationSettingDo) Offset(offset int) *userNotificationSettingDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userNotificationSettingDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *userNotificationSettingDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userNotificationSettingDo) Unscoped() *userNotificationSettingDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userNotificationSettingDo) Create(values ...*ai_boilerplate_model.UserNotificationSetting) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userNotificationSettingDo) CreateInBatches(values []*ai_boilerplate_model.UserNotificationSetting, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userNotificationSettingDo) Save(values ...*ai_boilerplate_model.UserNotificationSetting) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userNotificationSettingDo) First() (*ai_boilerplate_model.UserNotificationSetting, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*ai_boilerplate_model.UserNotificationSetting), nil
	}
}

func (u userNotificationSettingDo) Take() (*ai_boilerplate_model.UserNotificationSetting, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*ai_boilerplate_model.UserNotificationSetting), nil
	}
}

func (u userNotificationSettingDo) Last() (*ai_boilerplate_model.UserNotificationSetting, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*ai_boilerplate_model.UserNotificationSetting), nil
	}
}

func (u userNotificationSettingDo) Find() ([]*ai_boilerplate_model.UserNotificationSetting, error) {
	result, err := u.DO.Find()
	return result.([]*ai_boilerplate_model.UserNotificationSetting), err
}

func (u userNotificationSettingDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*ai_boilerplate_model.UserNotificationSetting, err error) {
	buf := make([]*ai_boilerplate_model.UserNotificationSetting, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userNotificationSettingDo) FindInBatches(result *[]*ai_boilerplate_model.UserNotificationSetting, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userNotificationSettingDo) Attrs(attrs ...field.AssignExpr) *userNotificationSettingDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userNotificationSettingDo) Assign(attrs ...field.AssignExpr) *userNotificationSettingDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userNotificationSettingDo) Joins(fields ...field.RelationField) *userNotificationSettingDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userNotificationSettingDo) Preload(fields ...field.RelationField) *userNotificationSettingDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userNotificationSettingDo) FirstOrInit() (*ai_boilerplate_model.UserNotificationSetting, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*ai_boilerplate_model.UserNotificationSetting), nil
	}
}

func (u userNotificationSettingDo) FirstOrCreate() (*ai_boilerplate_model.UserNotificationSetting, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*ai_boilerplate_model.UserNotificationSetting), nil
	}
}

func (u userNotificationSettingDo) FindByPage(offset int, limit int) (result []*ai_boilerplate_model.UserNotificationSetting, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userNotificationSettingDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userNotificationSettingDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userNotificationSettingDo) Delete(models ...*ai_boilerplate_model.UserNotificationSetting) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userNotificationSettingDo) withDO(do gen.Dao) *userNotificationSettingDo {
	u.DO = *do.(*gen.DO)
	return u
}
