// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.5.3
// - protoc             v3.21.9
// source: app/v1/activity.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationActivityListActivities = "/app.v1.Activity/ListActivities"

type ActivityHTTPServer interface {
	ListActivities(context.Context, *ListActivitiesReq) (*ListActivitiesReply, error)
}

func RegisterActivityHTTPServer(s *http.Server, srv ActivityHTTPServer) {
	r := s.Route("/")
	r.GET("/app/v1/activity/list", _Activity_ListActivities0_HTTP_Handler(srv))
}

func _Activity_ListActivities0_HTTP_Handler(srv ActivityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListActivitiesReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationActivityListActivities)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListActivities(ctx, req.(*ListActivitiesReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListActivitiesReply)
		return ctx.Result(200, reply)
	}
}

type ActivityHTTPClient interface {
	ListActivities(ctx context.Context, req *ListActivitiesReq, opts ...http.CallOption) (rsp *ListActivitiesReply, err error)
}

type ActivityHTTPClientImpl struct {
	cc *http.Client
}

func NewActivityHTTPClient(client *http.Client) ActivityHTTPClient {
	return &ActivityHTTPClientImpl{client}
}

func (c *ActivityHTTPClientImpl) ListActivities(ctx context.Context, in *ListActivitiesReq, opts ...http.CallOption) (*ListActivitiesReply, error) {
	var out ListActivitiesReply
	pattern := "/app/v1/activity/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationActivityListActivities))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
