// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: app/v1/app_version.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AppVersionClient is the client API for AppVersion service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AppVersionClient interface {
	// 检测版本更新
	CheckUpdate(ctx context.Context, in *CheckUpdateReq, opts ...grpc.CallOption) (*CheckUpdateReply, error)
}

type appVersionClient struct {
	cc grpc.ClientConnInterface
}

func NewAppVersionClient(cc grpc.ClientConnInterface) AppVersionClient {
	return &appVersionClient{cc}
}

func (c *appVersionClient) CheckUpdate(ctx context.Context, in *CheckUpdateReq, opts ...grpc.CallOption) (*CheckUpdateReply, error) {
	out := new(CheckUpdateReply)
	err := c.cc.Invoke(ctx, "/app.v1.AppVersion/CheckUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppVersionServer is the server API for AppVersion service.
// All implementations must embed UnimplementedAppVersionServer
// for forward compatibility
type AppVersionServer interface {
	// 检测版本更新
	CheckUpdate(context.Context, *CheckUpdateReq) (*CheckUpdateReply, error)
	mustEmbedUnimplementedAppVersionServer()
}

// UnimplementedAppVersionServer must be embedded to have forward compatible implementations.
type UnimplementedAppVersionServer struct {
}

func (UnimplementedAppVersionServer) CheckUpdate(context.Context, *CheckUpdateReq) (*CheckUpdateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckUpdate not implemented")
}
func (UnimplementedAppVersionServer) mustEmbedUnimplementedAppVersionServer() {}

// UnsafeAppVersionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppVersionServer will
// result in compilation errors.
type UnsafeAppVersionServer interface {
	mustEmbedUnimplementedAppVersionServer()
}

func RegisterAppVersionServer(s grpc.ServiceRegistrar, srv AppVersionServer) {
	s.RegisterService(&AppVersion_ServiceDesc, srv)
}

func _AppVersion_CheckUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppVersionServer).CheckUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.v1.AppVersion/CheckUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppVersionServer).CheckUpdate(ctx, req.(*CheckUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AppVersion_ServiceDesc is the grpc.ServiceDesc for AppVersion service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AppVersion_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "app.v1.AppVersion",
	HandlerType: (*AppVersionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckUpdate",
			Handler:    _AppVersion_CheckUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/v1/app_version.proto",
}
