// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.5.3
// - protoc             v3.21.9
// source: app/v1/banner.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationBannerListBanners = "/app.v1.Banner/ListBanners"

type BannerHTTPServer interface {
	ListBanners(context.Context, *ListBannersReq) (*ListBannersReply, error)
}

func RegisterBannerHTTPServer(s *http.Server, srv BannerHTTPServer) {
	r := s.Route("/")
	r.GET("/app/v1/banner/list", _Banner_ListBanners0_HTTP_Handler(srv))
}

func _Banner_ListBanners0_HTTP_Handler(srv BannerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListBannersReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBannerListBanners)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListBanners(ctx, req.(*ListBannersReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListBannersReply)
		return ctx.Result(200, reply)
	}
}

type BannerHTTPClient interface {
	ListBanners(ctx context.Context, req *ListBannersReq, opts ...http.CallOption) (rsp *ListBannersReply, err error)
}

type BannerHTTPClientImpl struct {
	cc *http.Client
}

func NewBannerHTTPClient(client *http.Client) BannerHTTPClient {
	return &BannerHTTPClientImpl{client}
}

func (c *BannerHTTPClientImpl) ListBanners(ctx context.Context, in *ListBannersReq, opts ...http.CallOption) (*ListBannersReply, error) {
	var out ListBannersReply
	pattern := "/app/v1/banner/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBannerListBanners))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
