// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.5.3
// - protoc             v3.21.9
// source: app/v1/help_faq.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationHelpFaqListHelpFaqs = "/app.v1.HelpFaq/ListHelpFaqs"

type HelpFaqHTTPServer interface {
	ListHelpFaqs(context.Context, *ListHelpFaqsReq) (*ListHelpFaqsReply, error)
}

func RegisterHelpFaqHTTPServer(s *http.Server, srv HelpFaqHTTPServer) {
	r := s.Route("/")
	r.GET("/app/v1/help/faqs", _HelpFaq_ListHelpFaqs0_HTTP_Handler(srv))
}

func _HelpFaq_ListHelpFaqs0_HTTP_Handler(srv HelpFaqHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListHelpFaqsReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHelpFaqListHelpFaqs)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListHelpFaqs(ctx, req.(*ListHelpFaqsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListHelpFaqsReply)
		return ctx.Result(200, reply)
	}
}

type HelpFaqHTTPClient interface {
	ListHelpFaqs(ctx context.Context, req *ListHelpFaqsReq, opts ...http.CallOption) (rsp *ListHelpFaqsReply, err error)
}

type HelpFaqHTTPClientImpl struct {
	cc *http.Client
}

func NewHelpFaqHTTPClient(client *http.Client) HelpFaqHTTPClient {
	return &HelpFaqHTTPClientImpl{client}
}

func (c *HelpFaqHTTPClientImpl) ListHelpFaqs(ctx context.Context, in *ListHelpFaqsReq, opts ...http.CallOption) (*ListHelpFaqsReply, error) {
	var out ListHelpFaqsReply
	pattern := "/app/v1/help/faqs"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHelpFaqListHelpFaqs))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
