// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: app/v1/help_category.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HelpCategoryClient is the client API for HelpCategory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HelpCategoryClient interface {
	// 帮助分类表-列表数据查询
	ListHelpCategories(ctx context.Context, in *ListHelpCategoriesReq, opts ...grpc.CallOption) (*ListHelpCategoriesReply, error)
}

type helpCategoryClient struct {
	cc grpc.ClientConnInterface
}

func NewHelpCategoryClient(cc grpc.ClientConnInterface) HelpCategoryClient {
	return &helpCategoryClient{cc}
}

func (c *helpCategoryClient) ListHelpCategories(ctx context.Context, in *ListHelpCategoriesReq, opts ...grpc.CallOption) (*ListHelpCategoriesReply, error) {
	out := new(ListHelpCategoriesReply)
	err := c.cc.Invoke(ctx, "/app.v1.HelpCategory/ListHelpCategories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelpCategoryServer is the server API for HelpCategory service.
// All implementations must embed UnimplementedHelpCategoryServer
// for forward compatibility
type HelpCategoryServer interface {
	// 帮助分类表-列表数据查询
	ListHelpCategories(context.Context, *ListHelpCategoriesReq) (*ListHelpCategoriesReply, error)
	mustEmbedUnimplementedHelpCategoryServer()
}

// UnimplementedHelpCategoryServer must be embedded to have forward compatible implementations.
type UnimplementedHelpCategoryServer struct {
}

func (UnimplementedHelpCategoryServer) ListHelpCategories(context.Context, *ListHelpCategoriesReq) (*ListHelpCategoriesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHelpCategories not implemented")
}
func (UnimplementedHelpCategoryServer) mustEmbedUnimplementedHelpCategoryServer() {}

// UnsafeHelpCategoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HelpCategoryServer will
// result in compilation errors.
type UnsafeHelpCategoryServer interface {
	mustEmbedUnimplementedHelpCategoryServer()
}

func RegisterHelpCategoryServer(s grpc.ServiceRegistrar, srv HelpCategoryServer) {
	s.RegisterService(&HelpCategory_ServiceDesc, srv)
}

func _HelpCategory_ListHelpCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHelpCategoriesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelpCategoryServer).ListHelpCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.v1.HelpCategory/ListHelpCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelpCategoryServer).ListHelpCategories(ctx, req.(*ListHelpCategoriesReq))
	}
	return interceptor(ctx, in, info, handler)
}

// HelpCategory_ServiceDesc is the grpc.ServiceDesc for HelpCategory service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HelpCategory_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "app.v1.HelpCategory",
	HandlerType: (*HelpCategoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListHelpCategories",
			Handler:    _HelpCategory_ListHelpCategories_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/v1/help_category.proto",
}
