// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: app/v1/help_feedback.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HelpFeedbackClient is the client API for HelpFeedback service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HelpFeedbackClient interface {
	// 用户反馈表-提交反馈
	SubmitFeedback(ctx context.Context, in *SubmitFeedbackReq, opts ...grpc.CallOption) (*SubmitFeedbackReply, error)
}

type helpFeedbackClient struct {
	cc grpc.ClientConnInterface
}

func NewHelpFeedbackClient(cc grpc.ClientConnInterface) HelpFeedbackClient {
	return &helpFeedbackClient{cc}
}

func (c *helpFeedbackClient) SubmitFeedback(ctx context.Context, in *SubmitFeedbackReq, opts ...grpc.CallOption) (*SubmitFeedbackReply, error) {
	out := new(SubmitFeedbackReply)
	err := c.cc.Invoke(ctx, "/app.v1.HelpFeedback/SubmitFeedback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelpFeedbackServer is the server API for HelpFeedback service.
// All implementations must embed UnimplementedHelpFeedbackServer
// for forward compatibility
type HelpFeedbackServer interface {
	// 用户反馈表-提交反馈
	SubmitFeedback(context.Context, *SubmitFeedbackReq) (*SubmitFeedbackReply, error)
	mustEmbedUnimplementedHelpFeedbackServer()
}

// UnimplementedHelpFeedbackServer must be embedded to have forward compatible implementations.
type UnimplementedHelpFeedbackServer struct {
}

func (UnimplementedHelpFeedbackServer) SubmitFeedback(context.Context, *SubmitFeedbackReq) (*SubmitFeedbackReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitFeedback not implemented")
}
func (UnimplementedHelpFeedbackServer) mustEmbedUnimplementedHelpFeedbackServer() {}

// UnsafeHelpFeedbackServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HelpFeedbackServer will
// result in compilation errors.
type UnsafeHelpFeedbackServer interface {
	mustEmbedUnimplementedHelpFeedbackServer()
}

func RegisterHelpFeedbackServer(s grpc.ServiceRegistrar, srv HelpFeedbackServer) {
	s.RegisterService(&HelpFeedback_ServiceDesc, srv)
}

func _HelpFeedback_SubmitFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitFeedbackReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelpFeedbackServer).SubmitFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.v1.HelpFeedback/SubmitFeedback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelpFeedbackServer).SubmitFeedback(ctx, req.(*SubmitFeedbackReq))
	}
	return interceptor(ctx, in, info, handler)
}

// HelpFeedback_ServiceDesc is the grpc.ServiceDesc for HelpFeedback service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HelpFeedback_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "app.v1.HelpFeedback",
	HandlerType: (*HelpFeedbackServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitFeedback",
			Handler:    _HelpFeedback_SubmitFeedback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/v1/help_feedback.proto",
}
