// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.5.3
// - protoc             v3.21.9
// source: app/v1/home.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationHomeGetBannerList = "/app.v1.Home/GetBannerList"
const OperationHomeGetContentDetail = "/app.v1.Home/GetContentDetail"
const OperationHomeGetContentList = "/app.v1.Home/GetContentList"

type HomeHTTPServer interface {
	GetBannerList(context.Context, *GetBannerListReq) (*GetBannerListReply, error)
	GetContentDetail(context.Context, *GetContentDetailReq) (*GetContentDetailReply, error)
	GetContentList(context.Context, *GetContentListReq) (*GetContentListReply, error)
}

func RegisterHomeHTTPServer(s *http.Server, srv HomeHTTPServer) {
	r := s.Route("/")
	r.GET("/app/v1/home/banner/list", _Home_GetBannerList0_HTTP_Handler(srv))
	r.GET("/app/v1/home/content/list", _Home_GetContentList0_HTTP_Handler(srv))
	r.GET("/app/v1/home/content/detail", _Home_GetContentDetail0_HTTP_Handler(srv))
}

func _Home_GetBannerList0_HTTP_Handler(srv HomeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetBannerListReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHomeGetBannerList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetBannerList(ctx, req.(*GetBannerListReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetBannerListReply)
		return ctx.Result(200, reply)
	}
}

func _Home_GetContentList0_HTTP_Handler(srv HomeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetContentListReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHomeGetContentList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetContentList(ctx, req.(*GetContentListReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetContentListReply)
		return ctx.Result(200, reply)
	}
}

func _Home_GetContentDetail0_HTTP_Handler(srv HomeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetContentDetailReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHomeGetContentDetail)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetContentDetail(ctx, req.(*GetContentDetailReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetContentDetailReply)
		return ctx.Result(200, reply)
	}
}

type HomeHTTPClient interface {
	GetBannerList(ctx context.Context, req *GetBannerListReq, opts ...http.CallOption) (rsp *GetBannerListReply, err error)
	GetContentDetail(ctx context.Context, req *GetContentDetailReq, opts ...http.CallOption) (rsp *GetContentDetailReply, err error)
	GetContentList(ctx context.Context, req *GetContentListReq, opts ...http.CallOption) (rsp *GetContentListReply, err error)
}

type HomeHTTPClientImpl struct {
	cc *http.Client
}

func NewHomeHTTPClient(client *http.Client) HomeHTTPClient {
	return &HomeHTTPClientImpl{client}
}

func (c *HomeHTTPClientImpl) GetBannerList(ctx context.Context, in *GetBannerListReq, opts ...http.CallOption) (*GetBannerListReply, error) {
	var out GetBannerListReply
	pattern := "/app/v1/home/banner/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHomeGetBannerList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *HomeHTTPClientImpl) GetContentDetail(ctx context.Context, in *GetContentDetailReq, opts ...http.CallOption) (*GetContentDetailReply, error) {
	var out GetContentDetailReply
	pattern := "/app/v1/home/content/detail"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHomeGetContentDetail))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *HomeHTTPClientImpl) GetContentList(ctx context.Context, in *GetContentListReq, opts ...http.CallOption) (*GetContentListReply, error) {
	var out GetContentListReply
	pattern := "/app/v1/home/content/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHomeGetContentList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
