// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.5.3
// - protoc             v3.21.9
// source: app/v1/mall_activation_code.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationMallActivationCodeActivateMembershipByCode = "/app.v1.MallActivationCode/ActivateMembershipByCode"
const OperationMallActivationCodeListActivationCodeRedemptions = "/app.v1.MallActivationCode/ListActivationCodeRedemptions"

type MallActivationCodeHTTPServer interface {
	ActivateMembershipByCode(context.Context, *ActivateMembershipByCodeReq) (*ActivateMembershipByCodeReply, error)
	ListActivationCodeRedemptions(context.Context, *ListActivationCodeRedemptionsReq) (*ListActivationCodeRedemptionsReply, error)
}

func RegisterMallActivationCodeHTTPServer(s *http.Server, srv MallActivationCodeHTTPServer) {
	r := s.Route("/")
	r.POST("/app/v1/mall_activation_code/activate", _MallActivationCode_ActivateMembershipByCode0_HTTP_Handler(srv))
	r.GET("/app/v1/mall_activation_code/redemptions", _MallActivationCode_ListActivationCodeRedemptions0_HTTP_Handler(srv))
}

func _MallActivationCode_ActivateMembershipByCode0_HTTP_Handler(srv MallActivationCodeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ActivateMembershipByCodeReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMallActivationCodeActivateMembershipByCode)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ActivateMembershipByCode(ctx, req.(*ActivateMembershipByCodeReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ActivateMembershipByCodeReply)
		return ctx.Result(200, reply)
	}
}

func _MallActivationCode_ListActivationCodeRedemptions0_HTTP_Handler(srv MallActivationCodeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListActivationCodeRedemptionsReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMallActivationCodeListActivationCodeRedemptions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListActivationCodeRedemptions(ctx, req.(*ListActivationCodeRedemptionsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListActivationCodeRedemptionsReply)
		return ctx.Result(200, reply)
	}
}

type MallActivationCodeHTTPClient interface {
	ActivateMembershipByCode(ctx context.Context, req *ActivateMembershipByCodeReq, opts ...http.CallOption) (rsp *ActivateMembershipByCodeReply, err error)
	ListActivationCodeRedemptions(ctx context.Context, req *ListActivationCodeRedemptionsReq, opts ...http.CallOption) (rsp *ListActivationCodeRedemptionsReply, err error)
}

type MallActivationCodeHTTPClientImpl struct {
	cc *http.Client
}

func NewMallActivationCodeHTTPClient(client *http.Client) MallActivationCodeHTTPClient {
	return &MallActivationCodeHTTPClientImpl{client}
}

func (c *MallActivationCodeHTTPClientImpl) ActivateMembershipByCode(ctx context.Context, in *ActivateMembershipByCodeReq, opts ...http.CallOption) (*ActivateMembershipByCodeReply, error) {
	var out ActivateMembershipByCodeReply
	pattern := "/app/v1/mall_activation_code/activate"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMallActivationCodeActivateMembershipByCode))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *MallActivationCodeHTTPClientImpl) ListActivationCodeRedemptions(ctx context.Context, in *ListActivationCodeRedemptionsReq, opts ...http.CallOption) (*ListActivationCodeRedemptionsReply, error) {
	var out ListActivationCodeRedemptionsReply
	pattern := "/app/v1/mall_activation_code/redemptions"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMallActivationCodeListActivationCodeRedemptions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
