// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: app/v1/mall_product.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on MembershipConfig with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *MembershipConfig) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MembershipConfig with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MembershipConfigMultiError, or nil if none found.
func (m *MembershipConfig) ValidateAll() error {
	return m.validate(true)
}

func (m *MembershipConfig) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for MembershipType

	// no validation rules for DurationDays

	if len(errors) > 0 {
		return MembershipConfigMultiError(errors)
	}

	return nil
}

// MembershipConfigMultiError is an error wrapping multiple validation errors
// returned by MembershipConfig.ValidateAll() if the designated constraints
// aren't met.
type MembershipConfigMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MembershipConfigMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MembershipConfigMultiError) AllErrors() []error { return m }

// MembershipConfigValidationError is the validation error returned by
// MembershipConfig.Validate if the designated constraints aren't met.
type MembershipConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MembershipConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MembershipConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MembershipConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MembershipConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MembershipConfigValidationError) ErrorName() string { return "MembershipConfigValidationError" }

// Error satisfies the builtin error interface
func (e MembershipConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMembershipConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MembershipConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MembershipConfigValidationError{}

// Validate checks the field values on ProductConfig with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ProductConfig) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProductConfig with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ProductConfigMultiError, or
// nil if none found.
func (m *ProductConfig) ValidateAll() error {
	return m.validate(true)
}

func (m *ProductConfig) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetMembership()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ProductConfigValidationError{
					field:  "Membership",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ProductConfigValidationError{
					field:  "Membership",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMembership()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ProductConfigValidationError{
				field:  "Membership",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ProductConfigMultiError(errors)
	}

	return nil
}

// ProductConfigMultiError is an error wrapping multiple validation errors
// returned by ProductConfig.ValidateAll() if the designated constraints
// aren't met.
type ProductConfigMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProductConfigMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProductConfigMultiError) AllErrors() []error { return m }

// ProductConfigValidationError is the validation error returned by
// ProductConfig.Validate if the designated constraints aren't met.
type ProductConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProductConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProductConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProductConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProductConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProductConfigValidationError) ErrorName() string { return "ProductConfigValidationError" }

// Error satisfies the builtin error interface
func (e ProductConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProductConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProductConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProductConfigValidationError{}

// Validate checks the field values on MallProductInfo with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *MallProductInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MallProductInfo with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MallProductInfoMultiError, or nil if none found.
func (m *MallProductInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *MallProductInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for ProductType

	// no validation rules for ProductName

	// no validation rules for ProductDesc

	if all {
		switch v := interface{}(m.GetProductConfig()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MallProductInfoValidationError{
					field:  "ProductConfig",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MallProductInfoValidationError{
					field:  "ProductConfig",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetProductConfig()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MallProductInfoValidationError{
				field:  "ProductConfig",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for OriginalPrice

	// no validation rules for CurrentPrice

	// no validation rules for StockQuantity

	// no validation rules for SoldQuantity

	// no validation rules for Sort

	// no validation rules for Status

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return MallProductInfoMultiError(errors)
	}

	return nil
}

// MallProductInfoMultiError is an error wrapping multiple validation errors
// returned by MallProductInfo.ValidateAll() if the designated constraints
// aren't met.
type MallProductInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MallProductInfoMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MallProductInfoMultiError) AllErrors() []error { return m }

// MallProductInfoValidationError is the validation error returned by
// MallProductInfo.Validate if the designated constraints aren't met.
type MallProductInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MallProductInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MallProductInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MallProductInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MallProductInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MallProductInfoValidationError) ErrorName() string { return "MallProductInfoValidationError" }

// Error satisfies the builtin error interface
func (e MallProductInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMallProductInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MallProductInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MallProductInfoValidationError{}

// Validate checks the field values on GetMallProductInfoReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetMallProductInfoReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetMallProductInfoReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetMallProductInfoReqMultiError, or nil if none found.
func (m *GetMallProductInfoReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetMallProductInfoReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return GetMallProductInfoReqMultiError(errors)
	}

	return nil
}

// GetMallProductInfoReqMultiError is an error wrapping multiple validation
// errors returned by GetMallProductInfoReq.ValidateAll() if the designated
// constraints aren't met.
type GetMallProductInfoReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetMallProductInfoReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetMallProductInfoReqMultiError) AllErrors() []error { return m }

// GetMallProductInfoReqValidationError is the validation error returned by
// GetMallProductInfoReq.Validate if the designated constraints aren't met.
type GetMallProductInfoReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetMallProductInfoReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetMallProductInfoReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetMallProductInfoReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetMallProductInfoReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetMallProductInfoReqValidationError) ErrorName() string {
	return "GetMallProductInfoReqValidationError"
}

// Error satisfies the builtin error interface
func (e GetMallProductInfoReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetMallProductInfoReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetMallProductInfoReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetMallProductInfoReqValidationError{}

// Validate checks the field values on GetMallProductInfoReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetMallProductInfoReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetMallProductInfoReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetMallProductInfoReplyMultiError, or nil if none found.
func (m *GetMallProductInfoReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetMallProductInfoReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetMallProductInfoReplyValidationError{
					field:  "Info",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetMallProductInfoReplyValidationError{
					field:  "Info",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetMallProductInfoReplyValidationError{
				field:  "Info",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetMallProductInfoReplyMultiError(errors)
	}

	return nil
}

// GetMallProductInfoReplyMultiError is an error wrapping multiple validation
// errors returned by GetMallProductInfoReply.ValidateAll() if the designated
// constraints aren't met.
type GetMallProductInfoReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetMallProductInfoReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetMallProductInfoReplyMultiError) AllErrors() []error { return m }

// GetMallProductInfoReplyValidationError is the validation error returned by
// GetMallProductInfoReply.Validate if the designated constraints aren't met.
type GetMallProductInfoReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetMallProductInfoReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetMallProductInfoReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetMallProductInfoReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetMallProductInfoReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetMallProductInfoReplyValidationError) ErrorName() string {
	return "GetMallProductInfoReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetMallProductInfoReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetMallProductInfoReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetMallProductInfoReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetMallProductInfoReplyValidationError{}

// Validate checks the field values on GetMembershipProductListReq with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetMembershipProductListReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetMembershipProductListReq with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetMembershipProductListReqMultiError, or nil if none found.
func (m *GetMembershipProductListReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetMembershipProductListReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetMembershipProductListReqMultiError(errors)
	}

	return nil
}

// GetMembershipProductListReqMultiError is an error wrapping multiple
// validation errors returned by GetMembershipProductListReq.ValidateAll() if
// the designated constraints aren't met.
type GetMembershipProductListReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetMembershipProductListReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetMembershipProductListReqMultiError) AllErrors() []error { return m }

// GetMembershipProductListReqValidationError is the validation error returned
// by GetMembershipProductListReq.Validate if the designated constraints
// aren't met.
type GetMembershipProductListReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetMembershipProductListReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetMembershipProductListReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetMembershipProductListReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetMembershipProductListReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetMembershipProductListReqValidationError) ErrorName() string {
	return "GetMembershipProductListReqValidationError"
}

// Error satisfies the builtin error interface
func (e GetMembershipProductListReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetMembershipProductListReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetMembershipProductListReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetMembershipProductListReqValidationError{}

// Validate checks the field values on GetMembershipProductListReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetMembershipProductListReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetMembershipProductListReply with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// GetMembershipProductListReplyMultiError, or nil if none found.
func (m *GetMembershipProductListReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetMembershipProductListReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetMembershipProductListReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetMembershipProductListReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetMembershipProductListReplyValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetMembershipProductListReplyMultiError(errors)
	}

	return nil
}

// GetMembershipProductListReplyMultiError is an error wrapping multiple
// validation errors returned by GetMembershipProductListReply.ValidateAll()
// if the designated constraints aren't met.
type GetMembershipProductListReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetMembershipProductListReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetMembershipProductListReplyMultiError) AllErrors() []error { return m }

// GetMembershipProductListReplyValidationError is the validation error
// returned by GetMembershipProductListReply.Validate if the designated
// constraints aren't met.
type GetMembershipProductListReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetMembershipProductListReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetMembershipProductListReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetMembershipProductListReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetMembershipProductListReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetMembershipProductListReplyValidationError) ErrorName() string {
	return "GetMembershipProductListReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetMembershipProductListReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetMembershipProductListReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetMembershipProductListReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetMembershipProductListReplyValidationError{}
