// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: app/v1/mall_product.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MallProductClient is the client API for MallProduct service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MallProductClient interface {
	// 获取商品详情
	GetMallProductInfo(ctx context.Context, in *GetMallProductInfoReq, opts ...grpc.CallOption) (*GetMallProductInfoReply, error)
	// 获取商品列表
	GetMallProductList(ctx context.Context, in *GetMallProductListReq, opts ...grpc.CallOption) (*GetMallProductListReply, error)
	// 购买商品
	PurchaseProduct(ctx context.Context, in *PurchaseProductReq, opts ...grpc.CallOption) (*PurchaseProductReply, error)
}

type mallProductClient struct {
	cc grpc.ClientConnInterface
}

func NewMallProductClient(cc grpc.ClientConnInterface) MallProductClient {
	return &mallProductClient{cc}
}

func (c *mallProductClient) GetMallProductInfo(ctx context.Context, in *GetMallProductInfoReq, opts ...grpc.CallOption) (*GetMallProductInfoReply, error) {
	out := new(GetMallProductInfoReply)
	err := c.cc.Invoke(ctx, "/app.v1.MallProduct/GetMallProductInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallProductClient) GetMallProductList(ctx context.Context, in *GetMallProductListReq, opts ...grpc.CallOption) (*GetMallProductListReply, error) {
	out := new(GetMallProductListReply)
	err := c.cc.Invoke(ctx, "/app.v1.MallProduct/GetMallProductList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallProductClient) PurchaseProduct(ctx context.Context, in *PurchaseProductReq, opts ...grpc.CallOption) (*PurchaseProductReply, error) {
	out := new(PurchaseProductReply)
	err := c.cc.Invoke(ctx, "/app.v1.MallProduct/PurchaseProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MallProductServer is the server API for MallProduct service.
// All implementations must embed UnimplementedMallProductServer
// for forward compatibility
type MallProductServer interface {
	// 获取商品详情
	GetMallProductInfo(context.Context, *GetMallProductInfoReq) (*GetMallProductInfoReply, error)
	// 获取商品列表
	GetMallProductList(context.Context, *GetMallProductListReq) (*GetMallProductListReply, error)
	// 购买商品
	PurchaseProduct(context.Context, *PurchaseProductReq) (*PurchaseProductReply, error)
	mustEmbedUnimplementedMallProductServer()
}

// UnimplementedMallProductServer must be embedded to have forward compatible implementations.
type UnimplementedMallProductServer struct {
}

func (UnimplementedMallProductServer) GetMallProductInfo(context.Context, *GetMallProductInfoReq) (*GetMallProductInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMallProductInfo not implemented")
}
func (UnimplementedMallProductServer) GetMallProductList(context.Context, *GetMallProductListReq) (*GetMallProductListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMallProductList not implemented")
}
func (UnimplementedMallProductServer) PurchaseProduct(context.Context, *PurchaseProductReq) (*PurchaseProductReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PurchaseProduct not implemented")
}
func (UnimplementedMallProductServer) mustEmbedUnimplementedMallProductServer() {}

// UnsafeMallProductServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MallProductServer will
// result in compilation errors.
type UnsafeMallProductServer interface {
	mustEmbedUnimplementedMallProductServer()
}

func RegisterMallProductServer(s grpc.ServiceRegistrar, srv MallProductServer) {
	s.RegisterService(&MallProduct_ServiceDesc, srv)
}

func _MallProduct_GetMallProductInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMallProductInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallProductServer).GetMallProductInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.v1.MallProduct/GetMallProductInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallProductServer).GetMallProductInfo(ctx, req.(*GetMallProductInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallProduct_GetMallProductList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMallProductListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallProductServer).GetMallProductList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.v1.MallProduct/GetMallProductList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallProductServer).GetMallProductList(ctx, req.(*GetMallProductListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallProduct_PurchaseProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurchaseProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallProductServer).PurchaseProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.v1.MallProduct/PurchaseProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallProductServer).PurchaseProduct(ctx, req.(*PurchaseProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

// MallProduct_ServiceDesc is the grpc.ServiceDesc for MallProduct service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MallProduct_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "app.v1.MallProduct",
	HandlerType: (*MallProductServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMallProductInfo",
			Handler:    _MallProduct_GetMallProductInfo_Handler,
		},
		{
			MethodName: "GetMallProductList",
			Handler:    _MallProduct_GetMallProductList_Handler,
		},
		{
			MethodName: "PurchaseProduct",
			Handler:    _MallProduct_PurchaseProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/v1/mall_product.proto",
}
