// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.5.3
// - protoc             v3.21.9
// source: app/v1/mall_order.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationMallOrderGetOrderInfo = "/app.v1.MallOrder/GetOrderInfo"
const OperationMallOrderGetPaymentInfo = "/app.v1.MallOrder/GetPaymentInfo"
const OperationMallOrderGetUserOrderList = "/app.v1.MallOrder/GetUserOrderList"
const OperationMallOrderPaymentCallback = "/app.v1.MallOrder/PaymentCallback"
const OperationMallOrderPlaceOrder = "/app.v1.MallOrder/PlaceOrder"

type MallOrderHTTPServer interface {
	GetOrderInfo(context.Context, *GetOrderInfoReq) (*GetOrderInfoReply, error)
	GetPaymentInfo(context.Context, *GetPaymentInfoReq) (*GetPaymentInfoReply, error)
	GetUserOrderList(context.Context, *GetUserOrderListReq) (*GetUserOrderListReply, error)
	PaymentCallback(context.Context, *PaymentCallbackReq) (*PaymentCallbackReply, error)
	PlaceOrder(context.Context, *PlaceOrderReq) (*PlaceOrderReply, error)
}

func RegisterMallOrderHTTPServer(s *http.Server, srv MallOrderHTTPServer) {
	r := s.Route("/")
	r.POST("/app/v1/mall_order/place", _MallOrder_PlaceOrder0_HTTP_Handler(srv))
	r.POST("/app/v1/mall_order/payment/info", _MallOrder_GetPaymentInfo0_HTTP_Handler(srv))
	r.POST("/app/v1/mall_order/payment/callback", _MallOrder_PaymentCallback0_HTTP_Handler(srv))
	r.GET("/app/v1/mall_order/order/info", _MallOrder_GetOrderInfo0_HTTP_Handler(srv))
	r.GET("/app/v1/mall_order/user/orders", _MallOrder_GetUserOrderList0_HTTP_Handler(srv))
}

func _MallOrder_PlaceOrder0_HTTP_Handler(srv MallOrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PlaceOrderReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMallOrderPlaceOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PlaceOrder(ctx, req.(*PlaceOrderReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PlaceOrderReply)
		return ctx.Result(200, reply)
	}
}

func _MallOrder_GetPaymentInfo0_HTTP_Handler(srv MallOrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPaymentInfoReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMallOrderGetPaymentInfo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPaymentInfo(ctx, req.(*GetPaymentInfoReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetPaymentInfoReply)
		return ctx.Result(200, reply)
	}
}

func _MallOrder_PaymentCallback0_HTTP_Handler(srv MallOrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PaymentCallbackReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMallOrderPaymentCallback)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PaymentCallback(ctx, req.(*PaymentCallbackReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PaymentCallbackReply)
		return ctx.Result(200, reply)
	}
}

func _MallOrder_GetOrderInfo0_HTTP_Handler(srv MallOrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetOrderInfoReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMallOrderGetOrderInfo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetOrderInfo(ctx, req.(*GetOrderInfoReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetOrderInfoReply)
		return ctx.Result(200, reply)
	}
}

func _MallOrder_GetUserOrderList0_HTTP_Handler(srv MallOrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUserOrderListReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMallOrderGetUserOrderList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUserOrderList(ctx, req.(*GetUserOrderListReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetUserOrderListReply)
		return ctx.Result(200, reply)
	}
}

type MallOrderHTTPClient interface {
	GetOrderInfo(ctx context.Context, req *GetOrderInfoReq, opts ...http.CallOption) (rsp *GetOrderInfoReply, err error)
	GetPaymentInfo(ctx context.Context, req *GetPaymentInfoReq, opts ...http.CallOption) (rsp *GetPaymentInfoReply, err error)
	GetUserOrderList(ctx context.Context, req *GetUserOrderListReq, opts ...http.CallOption) (rsp *GetUserOrderListReply, err error)
	PaymentCallback(ctx context.Context, req *PaymentCallbackReq, opts ...http.CallOption) (rsp *PaymentCallbackReply, err error)
	PlaceOrder(ctx context.Context, req *PlaceOrderReq, opts ...http.CallOption) (rsp *PlaceOrderReply, err error)
}

type MallOrderHTTPClientImpl struct {
	cc *http.Client
}

func NewMallOrderHTTPClient(client *http.Client) MallOrderHTTPClient {
	return &MallOrderHTTPClientImpl{client}
}

func (c *MallOrderHTTPClientImpl) GetOrderInfo(ctx context.Context, in *GetOrderInfoReq, opts ...http.CallOption) (*GetOrderInfoReply, error) {
	var out GetOrderInfoReply
	pattern := "/app/v1/mall_order/order/info"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMallOrderGetOrderInfo))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *MallOrderHTTPClientImpl) GetPaymentInfo(ctx context.Context, in *GetPaymentInfoReq, opts ...http.CallOption) (*GetPaymentInfoReply, error) {
	var out GetPaymentInfoReply
	pattern := "/app/v1/mall_order/payment/info"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMallOrderGetPaymentInfo))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *MallOrderHTTPClientImpl) GetUserOrderList(ctx context.Context, in *GetUserOrderListReq, opts ...http.CallOption) (*GetUserOrderListReply, error) {
	var out GetUserOrderListReply
	pattern := "/app/v1/mall_order/user/orders"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMallOrderGetUserOrderList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *MallOrderHTTPClientImpl) PaymentCallback(ctx context.Context, in *PaymentCallbackReq, opts ...http.CallOption) (*PaymentCallbackReply, error) {
	var out PaymentCallbackReply
	pattern := "/app/v1/mall_order/payment/callback"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMallOrderPaymentCallback))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *MallOrderHTTPClientImpl) PlaceOrder(ctx context.Context, in *PlaceOrderReq, opts ...http.CallOption) (*PlaceOrderReply, error) {
	var out PlaceOrderReply
	pattern := "/app/v1/mall_order/place"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMallOrderPlaceOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
