// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: app/v1/self_app_release.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CheckUpdateReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CheckUpdateReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CheckUpdateReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CheckUpdateReqMultiError,
// or nil if none found.
func (m *CheckUpdateReq) ValidateAll() error {
	return m.validate(true)
}

func (m *CheckUpdateReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PackageName

	// no validation rules for Channel

	// no validation rules for BuildNum

	// no validation rules for DeviceSn

	// no validation rules for OsVersion

	if len(errors) > 0 {
		return CheckUpdateReqMultiError(errors)
	}

	return nil
}

// CheckUpdateReqMultiError is an error wrapping multiple validation errors
// returned by CheckUpdateReq.ValidateAll() if the designated constraints
// aren't met.
type CheckUpdateReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CheckUpdateReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CheckUpdateReqMultiError) AllErrors() []error { return m }

// CheckUpdateReqValidationError is the validation error returned by
// CheckUpdateReq.Validate if the designated constraints aren't met.
type CheckUpdateReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CheckUpdateReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CheckUpdateReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CheckUpdateReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CheckUpdateReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CheckUpdateReqValidationError) ErrorName() string { return "CheckUpdateReqValidationError" }

// Error satisfies the builtin error interface
func (e CheckUpdateReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCheckUpdateReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CheckUpdateReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CheckUpdateReqValidationError{}

// Validate checks the field values on CheckUpdateReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CheckUpdateReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CheckUpdateReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CheckUpdateReplyMultiError, or nil if none found.
func (m *CheckUpdateReply) ValidateAll() error {
	return m.validate(true)
}

func (m *CheckUpdateReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for HasUpdate

	if all {
		switch v := interface{}(m.GetUpdateInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CheckUpdateReplyValidationError{
					field:  "UpdateInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CheckUpdateReplyValidationError{
					field:  "UpdateInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdateInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CheckUpdateReplyValidationError{
				field:  "UpdateInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CheckUpdateReplyMultiError(errors)
	}

	return nil
}

// CheckUpdateReplyMultiError is an error wrapping multiple validation errors
// returned by CheckUpdateReply.ValidateAll() if the designated constraints
// aren't met.
type CheckUpdateReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CheckUpdateReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CheckUpdateReplyMultiError) AllErrors() []error { return m }

// CheckUpdateReplyValidationError is the validation error returned by
// CheckUpdateReply.Validate if the designated constraints aren't met.
type CheckUpdateReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CheckUpdateReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CheckUpdateReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CheckUpdateReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CheckUpdateReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CheckUpdateReplyValidationError) ErrorName() string { return "CheckUpdateReplyValidationError" }

// Error satisfies the builtin error interface
func (e CheckUpdateReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCheckUpdateReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CheckUpdateReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CheckUpdateReplyValidationError{}

// Validate checks the field values on UpdateInfo with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UpdateInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UpdateInfoMultiError, or
// nil if none found.
func (m *UpdateInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Version

	// no validation rules for BuildNum

	// no validation rules for UpdateType

	// no validation rules for Title

	// no validation rules for Changelog

	// no validation rules for PackageURL

	// no validation rules for PackageSize

	// no validation rules for PackageMd5

	// no validation rules for MinOsVersion

	if len(errors) > 0 {
		return UpdateInfoMultiError(errors)
	}

	return nil
}

// UpdateInfoMultiError is an error wrapping multiple validation errors
// returned by UpdateInfo.ValidateAll() if the designated constraints aren't met.
type UpdateInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateInfoMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateInfoMultiError) AllErrors() []error { return m }

// UpdateInfoValidationError is the validation error returned by
// UpdateInfo.Validate if the designated constraints aren't met.
type UpdateInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateInfoValidationError) ErrorName() string { return "UpdateInfoValidationError" }

// Error satisfies the builtin error interface
func (e UpdateInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateInfoValidationError{}
