syntax = "proto3";

package app.v1;

import "buf/validate/validate.proto";
import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";

//import "google/protobuf/timestamp.proto";
//import "validate/validate.proto"; use buf first
option go_package = "github.com/fzf-labs/ai-boilerplate-backend/api/app/v1;v1";

//用户通知设置表
service UserNotificationSetting {
  //获取用户通知设置
  rpc GetNotificationSettings(GetNotificationSettingsReq) returns (GetNotificationSettingsReply) {
    option (google.api.http) = {get: "/app/v1/notification/settings"};
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "Bearer Token"
          type: STRING
          required: true
        }
      }
    };
  }
  //更新用户通知设置
  rpc UpdateNotificationSettings(UpdateNotificationSettingsReq) returns (UpdateNotificationSettingsReply) {
    option (google.api.http) = {
      post: "/app/v1/notification/settings"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "Bearer Token"
          type: STRING
          required: true
        }
      }
    };
  }
}

//用户通知设置信息
message NotificationSettingsInfo {
  string id = 1; // ID
  string userId = 2; // 用户ID
  repeated NotificationCategory categories = 3; // 通知类别
  string dndStartTime = 4; // 勿扰开始时间
  string dndEndTime = 5; // 勿扰结束时间
  string createdAt = 6; // 创建时间
  string updatedAt = 7; // 更新时间
}

//通知类别
message NotificationCategory {
  string key = 1; // 唯一标识
  string title = 2; // 标题
  string description = 3; // 描述
  bool enabled = 4; // 是否开启
}

//请求-获取用户通知设置
message GetNotificationSettingsReq {}

//响应-获取用户通知设置
message GetNotificationSettingsReply {
  NotificationSettingsInfo settings = 1;
}

//请求-更新用户通知设置
message UpdateNotificationSettingsReq {
  repeated NotificationPreference preferences = 1; // 通知偏好
  string dndStartTime = 2 [
    (buf.validate.field).ignore = IGNORE_IF_UNPOPULATED,
    (buf.validate.field).string = {
      min_len: 1
      max_len: 10
    }
  ]; // 勿扰开始时间（格式：HH:mm）
  string dndEndTime = 3 [
    (buf.validate.field).ignore = IGNORE_IF_UNPOPULATED,
    (buf.validate.field).string = {
      min_len: 1
      max_len: 10
    }
  ]; // 勿扰结束时间（格式：HH:mm）
}

//通知偏好
message NotificationPreference {
  string key = 1; // 唯一标识
  bool enabled = 2; // 是否开启
}

//响应-更新用户通知设置
message UpdateNotificationSettingsReply {}
